// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BoneData.proto
// Protobuf C++ Version: 6.32.0-dev

#include "BoneData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr BoneData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        index_{0u},
        tx_{0},
        ty_{0},
        tz_{0},
        qx_{0},
        qy_{0},
        qz_{0},
        qw_{0},
        sx_{0},
        sy_{0},
        sz_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BoneData_proto::BoneData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(BoneData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BoneData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoneData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoneData_protoDefaultTypeInternal() {}
  union {
    BoneData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoneData_protoDefaultTypeInternal _BoneData_proto_default_instance_;

inline constexpr FrameData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pobonedata_{},
        time_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FrameData_proto::FrameData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(FrameData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FrameData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameData_protoDefaultTypeInternal() {}
  union {
    FrameData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameData_protoDefaultTypeInternal _FrameData_proto_default_instance_;

inline constexpr AnimData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        poframedata_{},
        pname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        numbones_{0u},
        numframes_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR AnimData_proto::AnimData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(AnimData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnimData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimData_protoDefaultTypeInternal() {}
  union {
    AnimData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimData_protoDefaultTypeInternal _AnimData_proto_default_instance_;
// ===================================================================

class BoneData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BoneData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_._has_bits_);
};

BoneData_proto::BoneData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, BoneData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BoneData_proto)
}
BoneData_proto::BoneData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BoneData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, BoneData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE BoneData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void BoneData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, index_),
           0,
           offsetof(Impl_, sz_) -
               offsetof(Impl_, index_) +
               sizeof(Impl_::sz_));
}
BoneData_proto::~BoneData_proto() {
  // @@protoc_insertion_point(destructor:BoneData_proto)
  SharedDtor(*this);
}
inline void BoneData_proto::SharedDtor(MessageLite& self) {
  BoneData_proto& this_ = static_cast<BoneData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BoneData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BoneData_proto(arena);
}
constexpr auto BoneData_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BoneData_proto),
                                            alignof(BoneData_proto));
}
constexpr auto BoneData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_BoneData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BoneData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<BoneData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BoneData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<BoneData_proto>(), &BoneData_proto::ByteSizeLong,
              &BoneData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_._cached_size_),
          true,
      },
      "BoneData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> BoneData_proto_class_data_ =
    BoneData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BoneData_proto::GetClassData() const {
  return BoneData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 0, 0, 2>
BoneData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BoneData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::BoneData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 index = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.index_)}},
    // optional float tx = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.tx_)}},
    // optional float ty = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.ty_)}},
    // optional float tz = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.tz_)}},
    // optional float qx = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 4, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qx_)}},
    // optional float qy = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 5, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qy_)}},
    // optional float qz = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 6, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qz_)}},
    // optional float qw = 8;
    {::_pbi::TcParser::FastF32S1,
     {69, 7, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qw_)}},
    // optional float sx = 9;
    {::_pbi::TcParser::FastF32S1,
     {77, 8, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sx_)}},
    // optional float sy = 10;
    {::_pbi::TcParser::FastF32S1,
     {85, 9, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sy_)}},
    // optional float sz = 11;
    {::_pbi::TcParser::FastF32S1,
     {93, 10, 0, PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sz_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 index = 1;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.index_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional float tx = 2;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.tx_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float ty = 3;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.ty_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float tz = 4;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.tz_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qx = 5;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qx_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qy = 6;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qy_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qz = 7;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qz_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qw = 8;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.qw_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float sx = 9;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sx_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float sy = 10;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sy_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float sz = 11;
    {PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sz_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void BoneData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:BoneData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    ::memset(&_impl_.index_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.qw_) -
        reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.qw_));
  }
  if ((cached_has_bits & 0x00000700U) != 0) {
    ::memset(&_impl_.sx_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sz_) -
        reinterpret_cast<char*>(&_impl_.sx_)) + sizeof(_impl_.sz_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BoneData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BoneData_proto& this_ = static_cast<const BoneData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BoneData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BoneData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:BoneData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 index = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_index(), target);
  }

  // optional float tx = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_tx(), target);
  }

  // optional float ty = 3;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_ty(), target);
  }

  // optional float tz = 4;
  if ((cached_has_bits & 0x00000008U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_tz(), target);
  }

  // optional float qx = 5;
  if ((cached_has_bits & 0x00000010U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this_._internal_qx(), target);
  }

  // optional float qy = 6;
  if ((cached_has_bits & 0x00000020U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this_._internal_qy(), target);
  }

  // optional float qz = 7;
  if ((cached_has_bits & 0x00000040U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this_._internal_qz(), target);
  }

  // optional float qw = 8;
  if ((cached_has_bits & 0x00000080U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this_._internal_qw(), target);
  }

  // optional float sx = 9;
  if ((cached_has_bits & 0x00000100U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        9, this_._internal_sx(), target);
  }

  // optional float sy = 10;
  if ((cached_has_bits & 0x00000200U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        10, this_._internal_sy(), target);
  }

  // optional float sz = 11;
  if ((cached_has_bits & 0x00000400U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        11, this_._internal_sz(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BoneData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BoneData_proto::ByteSizeLong(const MessageLite& base) {
  const BoneData_proto& this_ = static_cast<const BoneData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BoneData_proto::ByteSizeLong() const {
  const BoneData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:BoneData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x000007feU & cached_has_bits) * 5;
   {
    // optional uint32 index = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_index());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void BoneData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BoneData_proto*>(&to_msg);
  auto& from = static_cast<const BoneData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BoneData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_impl_.index_ = from._impl_.index_;
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.tx_ = from._impl_.tx_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.ty_ = from._impl_.ty_;
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _this->_impl_.tz_ = from._impl_.tz_;
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      _this->_impl_.qx_ = from._impl_.qx_;
    }
    if ((cached_has_bits & 0x00000020U) != 0) {
      _this->_impl_.qy_ = from._impl_.qy_;
    }
    if ((cached_has_bits & 0x00000040U) != 0) {
      _this->_impl_.qz_ = from._impl_.qz_;
    }
    if ((cached_has_bits & 0x00000080U) != 0) {
      _this->_impl_.qw_ = from._impl_.qw_;
    }
  }
  if ((cached_has_bits & 0x00000700U) != 0) {
    if ((cached_has_bits & 0x00000100U) != 0) {
      _this->_impl_.sx_ = from._impl_.sx_;
    }
    if ((cached_has_bits & 0x00000200U) != 0) {
      _this->_impl_.sy_ = from._impl_.sy_;
    }
    if ((cached_has_bits & 0x00000400U) != 0) {
      _this->_impl_.sz_ = from._impl_.sz_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void BoneData_proto::CopyFrom(const BoneData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BoneData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BoneData_proto::InternalSwap(BoneData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.sz_)
      + sizeof(BoneData_proto::_impl_.sz_)
      - PROTOBUF_FIELD_OFFSET(BoneData_proto, _impl_.index_)>(
          reinterpret_cast<char*>(&_impl_.index_),
          reinterpret_cast<char*>(&other->_impl_.index_));
}

// ===================================================================

class FrameData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FrameData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_._has_bits_);
};

FrameData_proto::FrameData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, FrameData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FrameData_proto)
}
PROTOBUF_NDEBUG_INLINE FrameData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::FrameData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pobonedata_{visibility, arena, from.pobonedata_} {}

FrameData_proto::FrameData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FrameData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, FrameData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FrameData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.time_ = from._impl_.time_;

  // @@protoc_insertion_point(copy_constructor:FrameData_proto)
}
PROTOBUF_NDEBUG_INLINE FrameData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pobonedata_{visibility, arena} {}

inline void FrameData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.time_ = {};
}
FrameData_proto::~FrameData_proto() {
  // @@protoc_insertion_point(destructor:FrameData_proto)
  SharedDtor(*this);
}
inline void FrameData_proto::SharedDtor(MessageLite& self) {
  FrameData_proto& this_ = static_cast<FrameData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FrameData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FrameData_proto(arena);
}
constexpr auto FrameData_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_.pobonedata_) +
          decltype(FrameData_proto::_impl_.pobonedata_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(FrameData_proto), alignof(FrameData_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&FrameData_proto::PlacementNew_,
                                 sizeof(FrameData_proto),
                                 alignof(FrameData_proto));
  }
}
constexpr auto FrameData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<16>{
      {
          &_FrameData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FrameData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<FrameData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FrameData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<FrameData_proto>(), &FrameData_proto::ByteSizeLong,
              &FrameData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_._cached_size_),
          true,
      },
      "FrameData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<16> FrameData_proto_class_data_ =
    FrameData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FrameData_proto::GetClassData() const {
  return FrameData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
FrameData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    FrameData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FrameData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .BoneData_proto poBoneData = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_.pobonedata_)}},
    // optional float time = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0, PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_.time_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float time = 1;
    {PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_.time_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // repeated .BoneData_proto poBoneData = 2;
    {PROTOBUF_FIELD_OFFSET(FrameData_proto, _impl_.pobonedata_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::BoneData_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void FrameData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:FrameData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pobonedata_.Clear();
  _impl_.time_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FrameData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FrameData_proto& this_ = static_cast<const FrameData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FrameData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FrameData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:FrameData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional float time = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this_._internal_time(), target);
  }

  // repeated .BoneData_proto poBoneData = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_pobonedata_size());
       i < n; i++) {
    const auto& repfield = this_._internal_pobonedata().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FrameData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FrameData_proto::ByteSizeLong(const MessageLite& base) {
  const FrameData_proto& this_ = static_cast<const FrameData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FrameData_proto::ByteSizeLong() const {
  const FrameData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:FrameData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .BoneData_proto poBoneData = 2;
    {
      total_size += 1UL * this_._internal_pobonedata_size();
      for (const auto& msg : this_._internal_pobonedata()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000001U & cached_has_bits) * 5;
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void FrameData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FrameData_proto*>(&to_msg);
  auto& from = static_cast<const FrameData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FrameData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pobonedata()->MergeFrom(
      from._internal_pobonedata());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _this->_impl_.time_ = from._impl_.time_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void FrameData_proto::CopyFrom(const FrameData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FrameData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FrameData_proto::InternalSwap(FrameData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pobonedata_.InternalSwap(&other->_impl_.pobonedata_);
  swap(_impl_.time_, other->_impl_.time_);
}

// ===================================================================

class AnimData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AnimData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_._has_bits_);
};

AnimData_proto::AnimData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnimData_proto)
}
PROTOBUF_NDEBUG_INLINE AnimData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::AnimData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        poframedata_{visibility, arena, from.poframedata_},
        pname_(arena, from.pname_) {}

AnimData_proto::AnimData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AnimData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AnimData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numbones_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, numbones_),
           offsetof(Impl_, numframes_) -
               offsetof(Impl_, numbones_) +
               sizeof(Impl_::numframes_));

  // @@protoc_insertion_point(copy_constructor:AnimData_proto)
}
PROTOBUF_NDEBUG_INLINE AnimData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        poframedata_{visibility, arena},
        pname_(arena) {}

inline void AnimData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numbones_),
           0,
           offsetof(Impl_, numframes_) -
               offsetof(Impl_, numbones_) +
               sizeof(Impl_::numframes_));
}
AnimData_proto::~AnimData_proto() {
  // @@protoc_insertion_point(destructor:AnimData_proto)
  SharedDtor(*this);
}
inline void AnimData_proto::SharedDtor(MessageLite& self) {
  AnimData_proto& this_ = static_cast<AnimData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AnimData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AnimData_proto(arena);
}
constexpr auto AnimData_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.poframedata_) +
          decltype(AnimData_proto::_impl_.poframedata_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(AnimData_proto), alignof(AnimData_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AnimData_proto::PlacementNew_,
                                 sizeof(AnimData_proto),
                                 alignof(AnimData_proto));
  }
}
constexpr auto AnimData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_AnimData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AnimData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<AnimData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AnimData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<AnimData_proto>(), &AnimData_proto::ByteSizeLong,
              &AnimData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_._cached_size_),
          true,
      },
      "AnimData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> AnimData_proto_class_data_ =
    AnimData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AnimData_proto::GetClassData() const {
  return AnimData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 28, 2>
AnimData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AnimData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnimData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .FrameData_proto poFrameData = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.poframedata_)}},
    // optional string pName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.pname_)}},
    // optional uint32 numBones = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.numbones_)}},
    // optional uint32 numFrames = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.numframes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string pName = 1;
    {PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.pname_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional uint32 numBones = 2;
    {PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.numbones_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 numFrames = 3;
    {PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.numframes_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated .FrameData_proto poFrameData = 4;
    {PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.poframedata_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::FrameData_proto>()},
  }},
  {{
    "\16\5\0\0\0\0\0\0"
    "AnimData_proto"
    "pName"
  }},
};
PROTOBUF_NOINLINE void AnimData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:AnimData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poframedata_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.pname_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006U) != 0) {
    ::memset(&_impl_.numbones_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.numframes_) -
        reinterpret_cast<char*>(&_impl_.numbones_)) + sizeof(_impl_.numframes_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AnimData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AnimData_proto& this_ = static_cast<const AnimData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AnimData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AnimData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AnimData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string pName = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_pname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnimData_proto.pName");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional uint32 numBones = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_numbones(), target);
  }

  // optional uint32 numFrames = 3;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_numframes(), target);
  }

  // repeated .FrameData_proto poFrameData = 4;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_poframedata_size());
       i < n; i++) {
    const auto& repfield = this_._internal_poframedata().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            4, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AnimData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AnimData_proto::ByteSizeLong(const MessageLite& base) {
  const AnimData_proto& this_ = static_cast<const AnimData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AnimData_proto::ByteSizeLong() const {
  const AnimData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AnimData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .FrameData_proto poFrameData = 4;
    {
      total_size += 1UL * this_._internal_poframedata_size();
      for (const auto& msg : this_._internal_poframedata()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // optional string pName = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_pname());
    }
    // optional uint32 numBones = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numbones());
    }
    // optional uint32 numFrames = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numframes());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void AnimData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnimData_proto*>(&to_msg);
  auto& from = static_cast<const AnimData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnimData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_poframedata()->MergeFrom(
      from._internal_poframedata());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_pname(from._internal_pname());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.numbones_ = from._impl_.numbones_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.numframes_ = from._impl_.numframes_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void AnimData_proto::CopyFrom(const AnimData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnimData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnimData_proto::InternalSwap(AnimData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.poframedata_.InternalSwap(&other->_impl_.poframedata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pname_, &other->_impl_.pname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.numframes_)
      + sizeof(AnimData_proto::_impl_.numframes_)
      - PROTOBUF_FIELD_OFFSET(AnimData_proto, _impl_.numbones_)>(
          reinterpret_cast<char*>(&_impl_.numbones_),
          reinterpret_cast<char*>(&other->_impl_.numbones_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
