// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BoneData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef BoneData_2eproto_2epb_2eh
#define BoneData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_BoneData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_BoneData_2eproto {
  static const ::uint32_t offsets[];
};
class AnimData_proto;
struct AnimData_protoDefaultTypeInternal;
extern AnimData_protoDefaultTypeInternal _AnimData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> AnimData_proto_class_data_;
class BoneData_proto;
struct BoneData_protoDefaultTypeInternal;
extern BoneData_protoDefaultTypeInternal _BoneData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> BoneData_proto_class_data_;
class FrameData_proto;
struct FrameData_protoDefaultTypeInternal;
extern FrameData_protoDefaultTypeInternal _FrameData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<16> FrameData_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class BoneData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:BoneData_proto) */ {
 public:
  inline BoneData_proto() : BoneData_proto(nullptr) {}
  ~BoneData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BoneData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BoneData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoneData_proto(::google::protobuf::internal::ConstantInitialized);

  inline BoneData_proto(const BoneData_proto& from) : BoneData_proto(nullptr, from) {}
  inline BoneData_proto(BoneData_proto&& from) noexcept
      : BoneData_proto(nullptr, ::std::move(from)) {}
  inline BoneData_proto& operator=(const BoneData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoneData_proto& operator=(BoneData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const BoneData_proto& default_instance() {
    return *reinterpret_cast<const BoneData_proto*>(
        &_BoneData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BoneData_proto& a, BoneData_proto& b) { a.Swap(&b); }
  inline void Swap(BoneData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoneData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoneData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<BoneData_proto>(arena);
  }
  void CopyFrom(const BoneData_proto& from);
  void MergeFrom(const BoneData_proto& from) { BoneData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BoneData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "BoneData_proto"; }

 protected:
  explicit BoneData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BoneData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BoneData_proto& from);
  BoneData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BoneData_proto&& from) noexcept
      : BoneData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIndexFieldNumber = 1,
    kTxFieldNumber = 2,
    kTyFieldNumber = 3,
    kTzFieldNumber = 4,
    kQxFieldNumber = 5,
    kQyFieldNumber = 6,
    kQzFieldNumber = 7,
    kQwFieldNumber = 8,
    kSxFieldNumber = 9,
    kSyFieldNumber = 10,
    kSzFieldNumber = 11,
  };
  // optional uint32 index = 1;
  bool has_index() const;
  void clear_index() ;
  ::uint32_t index() const;
  void set_index(::uint32_t value);

  private:
  ::uint32_t _internal_index() const;
  void _internal_set_index(::uint32_t value);

  public:
  // optional float tx = 2;
  bool has_tx() const;
  void clear_tx() ;
  float tx() const;
  void set_tx(float value);

  private:
  float _internal_tx() const;
  void _internal_set_tx(float value);

  public:
  // optional float ty = 3;
  bool has_ty() const;
  void clear_ty() ;
  float ty() const;
  void set_ty(float value);

  private:
  float _internal_ty() const;
  void _internal_set_ty(float value);

  public:
  // optional float tz = 4;
  bool has_tz() const;
  void clear_tz() ;
  float tz() const;
  void set_tz(float value);

  private:
  float _internal_tz() const;
  void _internal_set_tz(float value);

  public:
  // optional float qx = 5;
  bool has_qx() const;
  void clear_qx() ;
  float qx() const;
  void set_qx(float value);

  private:
  float _internal_qx() const;
  void _internal_set_qx(float value);

  public:
  // optional float qy = 6;
  bool has_qy() const;
  void clear_qy() ;
  float qy() const;
  void set_qy(float value);

  private:
  float _internal_qy() const;
  void _internal_set_qy(float value);

  public:
  // optional float qz = 7;
  bool has_qz() const;
  void clear_qz() ;
  float qz() const;
  void set_qz(float value);

  private:
  float _internal_qz() const;
  void _internal_set_qz(float value);

  public:
  // optional float qw = 8;
  bool has_qw() const;
  void clear_qw() ;
  float qw() const;
  void set_qw(float value);

  private:
  float _internal_qw() const;
  void _internal_set_qw(float value);

  public:
  // optional float sx = 9;
  bool has_sx() const;
  void clear_sx() ;
  float sx() const;
  void set_sx(float value);

  private:
  float _internal_sx() const;
  void _internal_set_sx(float value);

  public:
  // optional float sy = 10;
  bool has_sy() const;
  void clear_sy() ;
  float sy() const;
  void set_sy(float value);

  private:
  float _internal_sy() const;
  void _internal_set_sy(float value);

  public:
  // optional float sz = 11;
  bool has_sz() const;
  void clear_sz() ;
  float sz() const;
  void set_sz(float value);

  private:
  float _internal_sz() const;
  void _internal_set_sz(float value);

  public:
  // @@protoc_insertion_point(class_scope:BoneData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 11,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BoneData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t index_;
    float tx_;
    float ty_;
    float tz_;
    float qx_;
    float qy_;
    float qz_;
    float qw_;
    float sx_;
    float sy_;
    float sz_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BoneData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> BoneData_proto_class_data_;
// -------------------------------------------------------------------

class FrameData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:FrameData_proto) */ {
 public:
  inline FrameData_proto() : FrameData_proto(nullptr) {}
  ~FrameData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FrameData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FrameData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FrameData_proto(::google::protobuf::internal::ConstantInitialized);

  inline FrameData_proto(const FrameData_proto& from) : FrameData_proto(nullptr, from) {}
  inline FrameData_proto(FrameData_proto&& from) noexcept
      : FrameData_proto(nullptr, ::std::move(from)) {}
  inline FrameData_proto& operator=(const FrameData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameData_proto& operator=(FrameData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const FrameData_proto& default_instance() {
    return *reinterpret_cast<const FrameData_proto*>(
        &_FrameData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(FrameData_proto& a, FrameData_proto& b) { a.Swap(&b); }
  inline void Swap(FrameData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<FrameData_proto>(arena);
  }
  void CopyFrom(const FrameData_proto& from);
  void MergeFrom(const FrameData_proto& from) { FrameData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FrameData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FrameData_proto"; }

 protected:
  explicit FrameData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FrameData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FrameData_proto& from);
  FrameData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FrameData_proto&& from) noexcept
      : FrameData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoBoneDataFieldNumber = 2,
    kTimeFieldNumber = 1,
  };
  // repeated .BoneData_proto poBoneData = 2;
  int pobonedata_size() const;
  private:
  int _internal_pobonedata_size() const;

  public:
  void clear_pobonedata() ;
  ::BoneData_proto* PROTOBUF_NONNULL mutable_pobonedata(int index);
  ::google::protobuf::RepeatedPtrField<::BoneData_proto>* PROTOBUF_NONNULL mutable_pobonedata();

  private:
  const ::google::protobuf::RepeatedPtrField<::BoneData_proto>& _internal_pobonedata() const;
  ::google::protobuf::RepeatedPtrField<::BoneData_proto>* PROTOBUF_NONNULL _internal_mutable_pobonedata();
  public:
  const ::BoneData_proto& pobonedata(int index) const;
  ::BoneData_proto* PROTOBUF_NONNULL add_pobonedata();
  const ::google::protobuf::RepeatedPtrField<::BoneData_proto>& pobonedata() const;
  // optional float time = 1;
  bool has_time() const;
  void clear_time() ;
  float time() const;
  void set_time(float value);

  private:
  float _internal_time() const;
  void _internal_set_time(float value);

  public:
  // @@protoc_insertion_point(class_scope:FrameData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FrameData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::BoneData_proto > pobonedata_;
    float time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BoneData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<16> FrameData_proto_class_data_;
// -------------------------------------------------------------------

class AnimData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:AnimData_proto) */ {
 public:
  inline AnimData_proto() : AnimData_proto(nullptr) {}
  ~AnimData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnimData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnimData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnimData_proto(::google::protobuf::internal::ConstantInitialized);

  inline AnimData_proto(const AnimData_proto& from) : AnimData_proto(nullptr, from) {}
  inline AnimData_proto(AnimData_proto&& from) noexcept
      : AnimData_proto(nullptr, ::std::move(from)) {}
  inline AnimData_proto& operator=(const AnimData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnimData_proto& operator=(AnimData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const AnimData_proto& default_instance() {
    return *reinterpret_cast<const AnimData_proto*>(
        &_AnimData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AnimData_proto& a, AnimData_proto& b) { a.Swap(&b); }
  inline void Swap(AnimData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnimData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnimData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<AnimData_proto>(arena);
  }
  void CopyFrom(const AnimData_proto& from);
  void MergeFrom(const AnimData_proto& from) { AnimData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnimData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AnimData_proto"; }

 protected:
  explicit AnimData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AnimData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AnimData_proto& from);
  AnimData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AnimData_proto&& from) noexcept
      : AnimData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoFrameDataFieldNumber = 4,
    kPNameFieldNumber = 1,
    kNumBonesFieldNumber = 2,
    kNumFramesFieldNumber = 3,
  };
  // repeated .FrameData_proto poFrameData = 4;
  int poframedata_size() const;
  private:
  int _internal_poframedata_size() const;

  public:
  void clear_poframedata() ;
  ::FrameData_proto* PROTOBUF_NONNULL mutable_poframedata(int index);
  ::google::protobuf::RepeatedPtrField<::FrameData_proto>* PROTOBUF_NONNULL mutable_poframedata();

  private:
  const ::google::protobuf::RepeatedPtrField<::FrameData_proto>& _internal_poframedata() const;
  ::google::protobuf::RepeatedPtrField<::FrameData_proto>* PROTOBUF_NONNULL _internal_mutable_poframedata();
  public:
  const ::FrameData_proto& poframedata(int index) const;
  ::FrameData_proto* PROTOBUF_NONNULL add_poframedata();
  const ::google::protobuf::RepeatedPtrField<::FrameData_proto>& poframedata() const;
  // optional string pName = 1;
  bool has_pname() const;
  void clear_pname() ;
  const ::std::string& pname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pname();
  void set_allocated_pname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pname();

  public:
  // optional uint32 numBones = 2;
  bool has_numbones() const;
  void clear_numbones() ;
  ::uint32_t numbones() const;
  void set_numbones(::uint32_t value);

  private:
  ::uint32_t _internal_numbones() const;
  void _internal_set_numbones(::uint32_t value);

  public:
  // optional uint32 numFrames = 3;
  bool has_numframes() const;
  void clear_numframes() ;
  ::uint32_t numframes() const;
  void set_numframes(::uint32_t value);

  private:
  ::uint32_t _internal_numframes() const;
  void _internal_set_numframes(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:AnimData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AnimData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::FrameData_proto > poframedata_;
    ::google::protobuf::internal::ArenaStringPtr pname_;
    ::uint32_t numbones_;
    ::uint32_t numframes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BoneData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> AnimData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BoneData_proto

// optional uint32 index = 1;
inline bool BoneData_proto::has_index() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void BoneData_proto::clear_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint32_t BoneData_proto::index() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.index)
  return _internal_index();
}
inline void BoneData_proto::set_index(::uint32_t value) {
  _internal_set_index(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:BoneData_proto.index)
}
inline ::uint32_t BoneData_proto::_internal_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.index_;
}
inline void BoneData_proto::_internal_set_index(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = value;
}

// optional float tx = 2;
inline bool BoneData_proto::has_tx() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void BoneData_proto::clear_tx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline float BoneData_proto::tx() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.tx)
  return _internal_tx();
}
inline void BoneData_proto::set_tx(float value) {
  _internal_set_tx(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:BoneData_proto.tx)
}
inline float BoneData_proto::_internal_tx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_;
}
inline void BoneData_proto::_internal_set_tx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_ = value;
}

// optional float ty = 3;
inline bool BoneData_proto::has_ty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void BoneData_proto::clear_ty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ty_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline float BoneData_proto::ty() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.ty)
  return _internal_ty();
}
inline void BoneData_proto::set_ty(float value) {
  _internal_set_ty(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:BoneData_proto.ty)
}
inline float BoneData_proto::_internal_ty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ty_;
}
inline void BoneData_proto::_internal_set_ty(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ty_ = value;
}

// optional float tz = 4;
inline bool BoneData_proto::has_tz() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void BoneData_proto::clear_tz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tz_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline float BoneData_proto::tz() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.tz)
  return _internal_tz();
}
inline void BoneData_proto::set_tz(float value) {
  _internal_set_tz(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:BoneData_proto.tz)
}
inline float BoneData_proto::_internal_tz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tz_;
}
inline void BoneData_proto::_internal_set_tz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tz_ = value;
}

// optional float qx = 5;
inline bool BoneData_proto::has_qx() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010U) != 0;
  return value;
}
inline void BoneData_proto::clear_qx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qx_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline float BoneData_proto::qx() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.qx)
  return _internal_qx();
}
inline void BoneData_proto::set_qx(float value) {
  _internal_set_qx(value);
  _impl_._has_bits_[0] |= 0x00000010U;
  // @@protoc_insertion_point(field_set:BoneData_proto.qx)
}
inline float BoneData_proto::_internal_qx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qx_;
}
inline void BoneData_proto::_internal_set_qx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qx_ = value;
}

// optional float qy = 6;
inline bool BoneData_proto::has_qy() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020U) != 0;
  return value;
}
inline void BoneData_proto::clear_qy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qy_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline float BoneData_proto::qy() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.qy)
  return _internal_qy();
}
inline void BoneData_proto::set_qy(float value) {
  _internal_set_qy(value);
  _impl_._has_bits_[0] |= 0x00000020U;
  // @@protoc_insertion_point(field_set:BoneData_proto.qy)
}
inline float BoneData_proto::_internal_qy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qy_;
}
inline void BoneData_proto::_internal_set_qy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qy_ = value;
}

// optional float qz = 7;
inline bool BoneData_proto::has_qz() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040U) != 0;
  return value;
}
inline void BoneData_proto::clear_qz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qz_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline float BoneData_proto::qz() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.qz)
  return _internal_qz();
}
inline void BoneData_proto::set_qz(float value) {
  _internal_set_qz(value);
  _impl_._has_bits_[0] |= 0x00000040U;
  // @@protoc_insertion_point(field_set:BoneData_proto.qz)
}
inline float BoneData_proto::_internal_qz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qz_;
}
inline void BoneData_proto::_internal_set_qz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qz_ = value;
}

// optional float qw = 8;
inline bool BoneData_proto::has_qw() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080U) != 0;
  return value;
}
inline void BoneData_proto::clear_qw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qw_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080U;
}
inline float BoneData_proto::qw() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.qw)
  return _internal_qw();
}
inline void BoneData_proto::set_qw(float value) {
  _internal_set_qw(value);
  _impl_._has_bits_[0] |= 0x00000080U;
  // @@protoc_insertion_point(field_set:BoneData_proto.qw)
}
inline float BoneData_proto::_internal_qw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qw_;
}
inline void BoneData_proto::_internal_set_qw(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qw_ = value;
}

// optional float sx = 9;
inline bool BoneData_proto::has_sx() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100U) != 0;
  return value;
}
inline void BoneData_proto::clear_sx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sx_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100U;
}
inline float BoneData_proto::sx() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.sx)
  return _internal_sx();
}
inline void BoneData_proto::set_sx(float value) {
  _internal_set_sx(value);
  _impl_._has_bits_[0] |= 0x00000100U;
  // @@protoc_insertion_point(field_set:BoneData_proto.sx)
}
inline float BoneData_proto::_internal_sx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sx_;
}
inline void BoneData_proto::_internal_set_sx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sx_ = value;
}

// optional float sy = 10;
inline bool BoneData_proto::has_sy() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200U) != 0;
  return value;
}
inline void BoneData_proto::clear_sy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sy_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200U;
}
inline float BoneData_proto::sy() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.sy)
  return _internal_sy();
}
inline void BoneData_proto::set_sy(float value) {
  _internal_set_sy(value);
  _impl_._has_bits_[0] |= 0x00000200U;
  // @@protoc_insertion_point(field_set:BoneData_proto.sy)
}
inline float BoneData_proto::_internal_sy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sy_;
}
inline void BoneData_proto::_internal_set_sy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sy_ = value;
}

// optional float sz = 11;
inline bool BoneData_proto::has_sz() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400U) != 0;
  return value;
}
inline void BoneData_proto::clear_sz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sz_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400U;
}
inline float BoneData_proto::sz() const {
  // @@protoc_insertion_point(field_get:BoneData_proto.sz)
  return _internal_sz();
}
inline void BoneData_proto::set_sz(float value) {
  _internal_set_sz(value);
  _impl_._has_bits_[0] |= 0x00000400U;
  // @@protoc_insertion_point(field_set:BoneData_proto.sz)
}
inline float BoneData_proto::_internal_sz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sz_;
}
inline void BoneData_proto::_internal_set_sz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sz_ = value;
}

// -------------------------------------------------------------------

// FrameData_proto

// optional float time = 1;
inline bool FrameData_proto::has_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void FrameData_proto::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline float FrameData_proto::time() const {
  // @@protoc_insertion_point(field_get:FrameData_proto.time)
  return _internal_time();
}
inline void FrameData_proto::set_time(float value) {
  _internal_set_time(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:FrameData_proto.time)
}
inline float FrameData_proto::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline void FrameData_proto::_internal_set_time(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = value;
}

// repeated .BoneData_proto poBoneData = 2;
inline int FrameData_proto::_internal_pobonedata_size() const {
  return _internal_pobonedata().size();
}
inline int FrameData_proto::pobonedata_size() const {
  return _internal_pobonedata_size();
}
inline void FrameData_proto::clear_pobonedata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pobonedata_.Clear();
}
inline ::BoneData_proto* PROTOBUF_NONNULL FrameData_proto::mutable_pobonedata(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:FrameData_proto.poBoneData)
  return _internal_mutable_pobonedata()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::BoneData_proto>* PROTOBUF_NONNULL FrameData_proto::mutable_pobonedata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:FrameData_proto.poBoneData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pobonedata();
}
inline const ::BoneData_proto& FrameData_proto::pobonedata(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FrameData_proto.poBoneData)
  return _internal_pobonedata().Get(index);
}
inline ::BoneData_proto* PROTOBUF_NONNULL FrameData_proto::add_pobonedata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::BoneData_proto* _add = _internal_mutable_pobonedata()->Add();
  // @@protoc_insertion_point(field_add:FrameData_proto.poBoneData)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::BoneData_proto>& FrameData_proto::pobonedata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:FrameData_proto.poBoneData)
  return _internal_pobonedata();
}
inline const ::google::protobuf::RepeatedPtrField<::BoneData_proto>&
FrameData_proto::_internal_pobonedata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pobonedata_;
}
inline ::google::protobuf::RepeatedPtrField<::BoneData_proto>* PROTOBUF_NONNULL
FrameData_proto::_internal_mutable_pobonedata() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pobonedata_;
}

// -------------------------------------------------------------------

// AnimData_proto

// optional string pName = 1;
inline bool AnimData_proto::has_pname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void AnimData_proto::clear_pname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& AnimData_proto::pname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimData_proto.pName)
  return _internal_pname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AnimData_proto::set_pname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:AnimData_proto.pName)
}
inline ::std::string* PROTOBUF_NONNULL AnimData_proto::mutable_pname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pname();
  // @@protoc_insertion_point(field_mutable:AnimData_proto.pName)
  return _s;
}
inline const ::std::string& AnimData_proto::_internal_pname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pname_.Get();
}
inline void AnimData_proto::_internal_set_pname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AnimData_proto::_internal_mutable_pname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AnimData_proto::release_pname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AnimData_proto.pName)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pname_.Set("", GetArena());
  }
  return released;
}
inline void AnimData_proto::set_allocated_pname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pname_.IsDefault()) {
    _impl_.pname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:AnimData_proto.pName)
}

// optional uint32 numBones = 2;
inline bool AnimData_proto::has_numbones() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void AnimData_proto::clear_numbones() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbones_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t AnimData_proto::numbones() const {
  // @@protoc_insertion_point(field_get:AnimData_proto.numBones)
  return _internal_numbones();
}
inline void AnimData_proto::set_numbones(::uint32_t value) {
  _internal_set_numbones(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:AnimData_proto.numBones)
}
inline ::uint32_t AnimData_proto::_internal_numbones() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numbones_;
}
inline void AnimData_proto::_internal_set_numbones(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbones_ = value;
}

// optional uint32 numFrames = 3;
inline bool AnimData_proto::has_numframes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void AnimData_proto::clear_numframes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numframes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::uint32_t AnimData_proto::numframes() const {
  // @@protoc_insertion_point(field_get:AnimData_proto.numFrames)
  return _internal_numframes();
}
inline void AnimData_proto::set_numframes(::uint32_t value) {
  _internal_set_numframes(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:AnimData_proto.numFrames)
}
inline ::uint32_t AnimData_proto::_internal_numframes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numframes_;
}
inline void AnimData_proto::_internal_set_numframes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numframes_ = value;
}

// repeated .FrameData_proto poFrameData = 4;
inline int AnimData_proto::_internal_poframedata_size() const {
  return _internal_poframedata().size();
}
inline int AnimData_proto::poframedata_size() const {
  return _internal_poframedata_size();
}
inline void AnimData_proto::clear_poframedata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.poframedata_.Clear();
}
inline ::FrameData_proto* PROTOBUF_NONNULL AnimData_proto::mutable_poframedata(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:AnimData_proto.poFrameData)
  return _internal_mutable_poframedata()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::FrameData_proto>* PROTOBUF_NONNULL AnimData_proto::mutable_poframedata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:AnimData_proto.poFrameData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_poframedata();
}
inline const ::FrameData_proto& AnimData_proto::poframedata(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimData_proto.poFrameData)
  return _internal_poframedata().Get(index);
}
inline ::FrameData_proto* PROTOBUF_NONNULL AnimData_proto::add_poframedata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::FrameData_proto* _add = _internal_mutable_poframedata()->Add();
  // @@protoc_insertion_point(field_add:AnimData_proto.poFrameData)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::FrameData_proto>& AnimData_proto::poframedata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:AnimData_proto.poFrameData)
  return _internal_poframedata();
}
inline const ::google::protobuf::RepeatedPtrField<::FrameData_proto>&
AnimData_proto::_internal_poframedata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.poframedata_;
}
inline ::google::protobuf::RepeatedPtrField<::FrameData_proto>* PROTOBUF_NONNULL
AnimData_proto::_internal_mutable_poframedata() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.poframedata_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // BoneData_2eproto_2epb_2eh
