// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meshData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef meshData_2eproto_2epb_2eh
#define meshData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
#include "vboData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_meshData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_meshData_2eproto {
  static const ::uint32_t offsets[];
};
enum meshData_proto_RENDER_MODE : int;
extern const uint32_t meshData_proto_RENDER_MODE_internal_data_[];
class meshData_proto;
struct meshData_protoDefaultTypeInternal;
extern meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> meshData_proto_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::meshData_proto_RENDER_MODE_internal_data_>
    internal::EnumTraitsImpl::value<::meshData_proto_RENDER_MODE>;
}  // namespace protobuf
}  // namespace google

enum meshData_proto_RENDER_MODE : int {
  meshData_proto_RENDER_MODE_MODE_POINTS = 0,
  meshData_proto_RENDER_MODE_MODE_LINE = 1,
  meshData_proto_RENDER_MODE_MODE_LINE_LOOP = 2,
  meshData_proto_RENDER_MODE_MODE_LINE_STRIP = 3,
  meshData_proto_RENDER_MODE_MODE_TRIANGLES = 4,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP = 5,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN = 6,
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t meshData_proto_RENDER_MODE_internal_data_[];
inline constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MIN =
    static_cast<meshData_proto_RENDER_MODE>(0);
inline constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MAX =
    static_cast<meshData_proto_RENDER_MODE>(6);
inline bool meshData_proto_RENDER_MODE_IsValid(int value) {
  return 0 <= value && value <= 6;
}
inline constexpr int meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE = 6 + 1;
const ::std::string& meshData_proto_RENDER_MODE_Name(meshData_proto_RENDER_MODE value);
template <typename T>
const ::std::string& meshData_proto_RENDER_MODE_Name(T value) {
  static_assert(::std::is_same<T, meshData_proto_RENDER_MODE>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RENDER_MODE_Name().");
  return meshData_proto_RENDER_MODE_Name(static_cast<meshData_proto_RENDER_MODE>(value));
}
bool meshData_proto_RENDER_MODE_Parse(
    ::absl::string_view name, meshData_proto_RENDER_MODE* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class meshData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:meshData_proto) */ {
 public:
  inline meshData_proto() : meshData_proto(nullptr) {}
  ~meshData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(meshData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(meshData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR meshData_proto(::google::protobuf::internal::ConstantInitialized);

  inline meshData_proto(const meshData_proto& from) : meshData_proto(nullptr, from) {}
  inline meshData_proto(meshData_proto&& from) noexcept
      : meshData_proto(nullptr, ::std::move(from)) {}
  inline meshData_proto& operator=(const meshData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline meshData_proto& operator=(meshData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const meshData_proto& default_instance() {
    return *reinterpret_cast<const meshData_proto*>(
        &_meshData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(meshData_proto& a, meshData_proto& b) { a.Swap(&b); }
  inline void Swap(meshData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(meshData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  meshData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<meshData_proto>(arena);
  }
  void CopyFrom(const meshData_proto& from);
  void MergeFrom(const meshData_proto& from) { meshData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(meshData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "meshData_proto"; }

 protected:
  explicit meshData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  meshData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const meshData_proto& from);
  meshData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, meshData_proto&& from) noexcept
      : meshData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using RENDER_MODE = meshData_proto_RENDER_MODE;
  static constexpr RENDER_MODE MODE_POINTS = meshData_proto_RENDER_MODE_MODE_POINTS;
  static constexpr RENDER_MODE MODE_LINE = meshData_proto_RENDER_MODE_MODE_LINE;
  static constexpr RENDER_MODE MODE_LINE_LOOP = meshData_proto_RENDER_MODE_MODE_LINE_LOOP;
  static constexpr RENDER_MODE MODE_LINE_STRIP = meshData_proto_RENDER_MODE_MODE_LINE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLES = meshData_proto_RENDER_MODE_MODE_TRIANGLES;
  static constexpr RENDER_MODE MODE_TRIANGLE_STRIP = meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLE_FAN = meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN;
  static inline bool RENDER_MODE_IsValid(int value) {
    return meshData_proto_RENDER_MODE_IsValid(value);
  }
  static constexpr RENDER_MODE RENDER_MODE_MIN = meshData_proto_RENDER_MODE_RENDER_MODE_MIN;
  static constexpr RENDER_MODE RENDER_MODE_MAX = meshData_proto_RENDER_MODE_RENDER_MODE_MAX;
  static constexpr int RENDER_MODE_ARRAYSIZE = meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& RENDER_MODE_Name(T value) {
    return meshData_proto_RENDER_MODE_Name(value);
  }
  static inline bool RENDER_MODE_Parse(
      ::absl::string_view name, RENDER_MODE* PROTOBUF_NONNULL value) {
    return meshData_proto_RENDER_MODE_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPMeshNameFieldNumber = 3,
    kModeFieldNumber = 4,
    kTriCountFieldNumber = 5,
    kVertCountFieldNumber = 6,
    kVboVertFieldNumber = 7,
    kVboNormFieldNumber = 8,
    kVboUvFieldNumber = 9,
    kVboIndexFieldNumber = 10,
    kVboColorFieldNumber = 11,
    kPVersionFieldNumber = 1,
    kMeshCountFieldNumber = 2,
  };
  // repeated bytes pMeshName = 3;
  int pmeshname_size() const;
  private:
  int _internal_pmeshname_size() const;

  public:
  void clear_pmeshname() ;
  const ::std::string& pmeshname(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_pmeshname(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pmeshname(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_pmeshname();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_pmeshname(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& pmeshname() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_pmeshname();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_pmeshname() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_pmeshname();

  public:
  // repeated .meshData_proto.RENDER_MODE mode = 4;
  int mode_size() const;
  private:
  int _internal_mode_size() const;

  public:
  void clear_mode() ;
  public:
  ::meshData_proto_RENDER_MODE mode(int index) const;
  void set_mode(int index, ::meshData_proto_RENDER_MODE value);
  void add_mode(::meshData_proto_RENDER_MODE value);
  const ::google::protobuf::RepeatedField<int>& mode() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL mutable_mode();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_mode() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL _internal_mutable_mode();

  public:
  // repeated uint32 triCount = 5;
  int tricount_size() const;
  private:
  int _internal_tricount_size() const;

  public:
  void clear_tricount() ;
  ::uint32_t tricount(int index) const;
  void set_tricount(int index, ::uint32_t value);
  void add_tricount(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& tricount() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_tricount();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_tricount() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_tricount();

  public:
  // repeated uint32 vertCount = 6;
  int vertcount_size() const;
  private:
  int _internal_vertcount_size() const;

  public:
  void clear_vertcount() ;
  ::uint32_t vertcount(int index) const;
  void set_vertcount(int index, ::uint32_t value);
  void add_vertcount(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& vertcount() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_vertcount();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_vertcount() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_vertcount();

  public:
  // repeated .vboData_proto vbo_vert = 7;
  int vbo_vert_size() const;
  private:
  int _internal_vbo_vert_size() const;

  public:
  void clear_vbo_vert() ;
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_vert(int index);
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL mutable_vbo_vert();

  private:
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& _internal_vbo_vert() const;
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL _internal_mutable_vbo_vert();
  public:
  const ::vboData_proto& vbo_vert(int index) const;
  ::vboData_proto* PROTOBUF_NONNULL add_vbo_vert();
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& vbo_vert() const;
  // repeated .vboData_proto vbo_norm = 8;
  int vbo_norm_size() const;
  private:
  int _internal_vbo_norm_size() const;

  public:
  void clear_vbo_norm() ;
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_norm(int index);
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL mutable_vbo_norm();

  private:
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& _internal_vbo_norm() const;
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL _internal_mutable_vbo_norm();
  public:
  const ::vboData_proto& vbo_norm(int index) const;
  ::vboData_proto* PROTOBUF_NONNULL add_vbo_norm();
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& vbo_norm() const;
  // repeated .vboData_proto vbo_uv = 9;
  int vbo_uv_size() const;
  private:
  int _internal_vbo_uv_size() const;

  public:
  void clear_vbo_uv() ;
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_uv(int index);
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL mutable_vbo_uv();

  private:
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& _internal_vbo_uv() const;
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL _internal_mutable_vbo_uv();
  public:
  const ::vboData_proto& vbo_uv(int index) const;
  ::vboData_proto* PROTOBUF_NONNULL add_vbo_uv();
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& vbo_uv() const;
  // repeated .vboData_proto vbo_index = 10;
  int vbo_index_size() const;
  private:
  int _internal_vbo_index_size() const;

  public:
  void clear_vbo_index() ;
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_index(int index);
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL mutable_vbo_index();

  private:
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& _internal_vbo_index() const;
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL _internal_mutable_vbo_index();
  public:
  const ::vboData_proto& vbo_index(int index) const;
  ::vboData_proto* PROTOBUF_NONNULL add_vbo_index();
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& vbo_index() const;
  // repeated .vboData_proto vbo_color = 11;
  int vbo_color_size() const;
  private:
  int _internal_vbo_color_size() const;

  public:
  void clear_vbo_color() ;
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_color(int index);
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL mutable_vbo_color();

  private:
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& _internal_vbo_color() const;
  ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL _internal_mutable_vbo_color();
  public:
  const ::vboData_proto& vbo_color(int index) const;
  ::vboData_proto* PROTOBUF_NONNULL add_vbo_color();
  const ::google::protobuf::RepeatedPtrField<::vboData_proto>& vbo_color() const;
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const ::std::string& pversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pversion();
  void set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pversion();

  public:
  // optional uint32 meshCount = 2;
  bool has_meshcount() const;
  void clear_meshcount() ;
  ::uint32_t meshcount() const;
  void set_meshcount(::uint32_t value);

  private:
  ::uint32_t _internal_meshcount() const;
  void _internal_set_meshcount(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:meshData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 11,
                                   5, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const meshData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> pmeshname_;
    ::google::protobuf::RepeatedField<int> mode_;
    ::google::protobuf::internal::CachedSize _mode_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> tricount_;
    ::google::protobuf::internal::CachedSize _tricount_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> vertcount_;
    ::google::protobuf::internal::CachedSize _vertcount_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField< ::vboData_proto > vbo_vert_;
    ::google::protobuf::RepeatedPtrField< ::vboData_proto > vbo_norm_;
    ::google::protobuf::RepeatedPtrField< ::vboData_proto > vbo_uv_;
    ::google::protobuf::RepeatedPtrField< ::vboData_proto > vbo_index_;
    ::google::protobuf::RepeatedPtrField< ::vboData_proto > vbo_color_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::uint32_t meshcount_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meshData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> meshData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// meshData_proto

// optional bytes pVersion = 1;
inline bool meshData_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void meshData_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& meshData_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void meshData_proto::set_pversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:meshData_proto.pVersion)
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::mutable_pversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:meshData_proto.pVersion)
  return _s;
}
inline const ::std::string& meshData_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void meshData_proto::_internal_set_pversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE meshData_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pversion_.Set("", GetArena());
  }
  return released;
}
inline void meshData_proto::set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pversion_.IsDefault()) {
    _impl_.pversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.pVersion)
}

// optional uint32 meshCount = 2;
inline bool meshData_proto::has_meshcount() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void meshData_proto::clear_meshcount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.meshcount_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t meshData_proto::meshcount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.meshCount)
  return _internal_meshcount();
}
inline void meshData_proto::set_meshcount(::uint32_t value) {
  _internal_set_meshcount(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:meshData_proto.meshCount)
}
inline ::uint32_t meshData_proto::_internal_meshcount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.meshcount_;
}
inline void meshData_proto::_internal_set_meshcount(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.meshcount_ = value;
}

// repeated bytes pMeshName = 3;
inline int meshData_proto::_internal_pmeshname_size() const {
  return _internal_pmeshname().size();
}
inline int meshData_proto::pmeshname_size() const {
  return _internal_pmeshname_size();
}
inline void meshData_proto::clear_pmeshname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pmeshname_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::add_pmeshname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_pmeshname()->Add();
  // @@protoc_insertion_point(field_add_mutable:meshData_proto.pMeshName)
  return _s;
}
inline const ::std::string& meshData_proto::pmeshname(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.pMeshName)
  return _internal_pmeshname().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::mutable_pmeshname(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:meshData_proto.pMeshName)
  return _internal_mutable_pmeshname()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void meshData_proto::set_pmeshname(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_pmeshname()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:meshData_proto.pMeshName)
}
template <typename Arg_, typename... Args_>
inline void meshData_proto::add_pmeshname(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_pmeshname(),
                               ::std::forward<Arg_>(value),
                               args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_add:meshData_proto.pMeshName)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& meshData_proto::pmeshname()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.pMeshName)
  return _internal_pmeshname();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
meshData_proto::mutable_pmeshname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.pMeshName)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pmeshname();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
meshData_proto::_internal_pmeshname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pmeshname_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_pmeshname() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pmeshname_;
}

// repeated .meshData_proto.RENDER_MODE mode = 4;
inline int meshData_proto::_internal_mode_size() const {
  return _internal_mode().size();
}
inline int meshData_proto::mode_size() const {
  return _internal_mode_size();
}
inline void meshData_proto::clear_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_.Clear();
}
inline ::meshData_proto_RENDER_MODE meshData_proto::mode(int index) const {
  // @@protoc_insertion_point(field_get:meshData_proto.mode)
  return static_cast<::meshData_proto_RENDER_MODE>(_internal_mode().Get(index));
}
inline void meshData_proto::set_mode(int index, ::meshData_proto_RENDER_MODE value) {
  _internal_mutable_mode()->Set(index, value);
  // @@protoc_insertion_point(field_set:meshData_proto.mode)
}
inline void meshData_proto::add_mode(::meshData_proto_RENDER_MODE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_mode()->Add(value);
  // @@protoc_insertion_point(field_add:meshData_proto.mode)
}
inline const ::google::protobuf::RepeatedField<int>& meshData_proto::mode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.mode)
  return _internal_mode();
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL meshData_proto::mutable_mode()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.mode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_mode();
}
inline const ::google::protobuf::RepeatedField<int>& meshData_proto::_internal_mode()
    const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mode_;
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_mode() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.mode_;
}

// repeated uint32 triCount = 5;
inline int meshData_proto::_internal_tricount_size() const {
  return _internal_tricount().size();
}
inline int meshData_proto::tricount_size() const {
  return _internal_tricount_size();
}
inline void meshData_proto::clear_tricount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tricount_.Clear();
}
inline ::uint32_t meshData_proto::tricount(int index) const {
  // @@protoc_insertion_point(field_get:meshData_proto.triCount)
  return _internal_tricount().Get(index);
}
inline void meshData_proto::set_tricount(int index, ::uint32_t value) {
  _internal_mutable_tricount()->Set(index, value);
  // @@protoc_insertion_point(field_set:meshData_proto.triCount)
}
inline void meshData_proto::add_tricount(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_tricount()->Add(value);
  // @@protoc_insertion_point(field_add:meshData_proto.triCount)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& meshData_proto::tricount() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.triCount)
  return _internal_tricount();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL meshData_proto::mutable_tricount()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.triCount)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tricount();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
meshData_proto::_internal_tricount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tricount_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_tricount() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tricount_;
}

// repeated uint32 vertCount = 6;
inline int meshData_proto::_internal_vertcount_size() const {
  return _internal_vertcount().size();
}
inline int meshData_proto::vertcount_size() const {
  return _internal_vertcount_size();
}
inline void meshData_proto::clear_vertcount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vertcount_.Clear();
}
inline ::uint32_t meshData_proto::vertcount(int index) const {
  // @@protoc_insertion_point(field_get:meshData_proto.vertCount)
  return _internal_vertcount().Get(index);
}
inline void meshData_proto::set_vertcount(int index, ::uint32_t value) {
  _internal_mutable_vertcount()->Set(index, value);
  // @@protoc_insertion_point(field_set:meshData_proto.vertCount)
}
inline void meshData_proto::add_vertcount(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_vertcount()->Add(value);
  // @@protoc_insertion_point(field_add:meshData_proto.vertCount)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& meshData_proto::vertcount() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.vertCount)
  return _internal_vertcount();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL meshData_proto::mutable_vertcount()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.vertCount)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vertcount();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
meshData_proto::_internal_vertcount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vertcount_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_vertcount() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vertcount_;
}

// repeated .vboData_proto vbo_vert = 7;
inline int meshData_proto::_internal_vbo_vert_size() const {
  return _internal_vbo_vert().size();
}
inline int meshData_proto::vbo_vert_size() const {
  return _internal_vbo_vert_size();
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_vert(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_vert)
  return _internal_mutable_vbo_vert()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL meshData_proto::mutable_vbo_vert()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.vbo_vert)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vbo_vert();
}
inline const ::vboData_proto& meshData_proto::vbo_vert(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_vert)
  return _internal_vbo_vert().Get(index);
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::add_vbo_vert()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::vboData_proto* _add = _internal_mutable_vbo_vert()->Add();
  // @@protoc_insertion_point(field_add:meshData_proto.vbo_vert)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>& meshData_proto::vbo_vert() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.vbo_vert)
  return _internal_vbo_vert();
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>&
meshData_proto::_internal_vbo_vert() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vbo_vert_;
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_vbo_vert() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vbo_vert_;
}

// repeated .vboData_proto vbo_norm = 8;
inline int meshData_proto::_internal_vbo_norm_size() const {
  return _internal_vbo_norm().size();
}
inline int meshData_proto::vbo_norm_size() const {
  return _internal_vbo_norm_size();
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_norm(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_norm)
  return _internal_mutable_vbo_norm()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL meshData_proto::mutable_vbo_norm()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.vbo_norm)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vbo_norm();
}
inline const ::vboData_proto& meshData_proto::vbo_norm(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_norm)
  return _internal_vbo_norm().Get(index);
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::add_vbo_norm()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::vboData_proto* _add = _internal_mutable_vbo_norm()->Add();
  // @@protoc_insertion_point(field_add:meshData_proto.vbo_norm)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>& meshData_proto::vbo_norm() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.vbo_norm)
  return _internal_vbo_norm();
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>&
meshData_proto::_internal_vbo_norm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vbo_norm_;
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_vbo_norm() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vbo_norm_;
}

// repeated .vboData_proto vbo_uv = 9;
inline int meshData_proto::_internal_vbo_uv_size() const {
  return _internal_vbo_uv().size();
}
inline int meshData_proto::vbo_uv_size() const {
  return _internal_vbo_uv_size();
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_uv(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_uv)
  return _internal_mutable_vbo_uv()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL meshData_proto::mutable_vbo_uv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.vbo_uv)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vbo_uv();
}
inline const ::vboData_proto& meshData_proto::vbo_uv(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_uv)
  return _internal_vbo_uv().Get(index);
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::add_vbo_uv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::vboData_proto* _add = _internal_mutable_vbo_uv()->Add();
  // @@protoc_insertion_point(field_add:meshData_proto.vbo_uv)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>& meshData_proto::vbo_uv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.vbo_uv)
  return _internal_vbo_uv();
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>&
meshData_proto::_internal_vbo_uv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vbo_uv_;
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_vbo_uv() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vbo_uv_;
}

// repeated .vboData_proto vbo_index = 10;
inline int meshData_proto::_internal_vbo_index_size() const {
  return _internal_vbo_index().size();
}
inline int meshData_proto::vbo_index_size() const {
  return _internal_vbo_index_size();
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_index(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_index)
  return _internal_mutable_vbo_index()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL meshData_proto::mutable_vbo_index()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.vbo_index)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vbo_index();
}
inline const ::vboData_proto& meshData_proto::vbo_index(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_index)
  return _internal_vbo_index().Get(index);
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::add_vbo_index()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::vboData_proto* _add = _internal_mutable_vbo_index()->Add();
  // @@protoc_insertion_point(field_add:meshData_proto.vbo_index)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>& meshData_proto::vbo_index() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.vbo_index)
  return _internal_vbo_index();
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>&
meshData_proto::_internal_vbo_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vbo_index_;
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_vbo_index() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vbo_index_;
}

// repeated .vboData_proto vbo_color = 11;
inline int meshData_proto::_internal_vbo_color_size() const {
  return _internal_vbo_color().size();
}
inline int meshData_proto::vbo_color_size() const {
  return _internal_vbo_color_size();
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_color(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_color)
  return _internal_mutable_vbo_color()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL meshData_proto::mutable_vbo_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:meshData_proto.vbo_color)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vbo_color();
}
inline const ::vboData_proto& meshData_proto::vbo_color(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_color)
  return _internal_vbo_color().Get(index);
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::add_vbo_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::vboData_proto* _add = _internal_mutable_vbo_color()->Add();
  // @@protoc_insertion_point(field_add:meshData_proto.vbo_color)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>& meshData_proto::vbo_color() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:meshData_proto.vbo_color)
  return _internal_vbo_color();
}
inline const ::google::protobuf::RepeatedPtrField<::vboData_proto>&
meshData_proto::_internal_vbo_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vbo_color_;
}
inline ::google::protobuf::RepeatedPtrField<::vboData_proto>* PROTOBUF_NONNULL
meshData_proto::_internal_mutable_vbo_color() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vbo_color_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::meshData_proto_RENDER_MODE> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // meshData_2eproto_2epb_2eh
