// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meshData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef meshData_2eproto_2epb_2eh
#define meshData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
#include "vboData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_meshData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_meshData_2eproto {
  static const ::uint32_t offsets[];
};
enum meshData_proto_RENDER_MODE : int;
extern const uint32_t meshData_proto_RENDER_MODE_internal_data_[];
class meshData_proto;
struct meshData_protoDefaultTypeInternal;
extern meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> meshData_proto_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::meshData_proto_RENDER_MODE_internal_data_>
    internal::EnumTraitsImpl::value<::meshData_proto_RENDER_MODE>;
}  // namespace protobuf
}  // namespace google

enum meshData_proto_RENDER_MODE : int {
  meshData_proto_RENDER_MODE_MODE_POINTS = 0,
  meshData_proto_RENDER_MODE_MODE_LINE = 1,
  meshData_proto_RENDER_MODE_MODE_LINE_LOOP = 2,
  meshData_proto_RENDER_MODE_MODE_LINE_STRIP = 3,
  meshData_proto_RENDER_MODE_MODE_TRIANGLES = 4,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP = 5,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN = 6,
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t meshData_proto_RENDER_MODE_internal_data_[];
inline constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MIN =
    static_cast<meshData_proto_RENDER_MODE>(0);
inline constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MAX =
    static_cast<meshData_proto_RENDER_MODE>(6);
inline bool meshData_proto_RENDER_MODE_IsValid(int value) {
  return 0 <= value && value <= 6;
}
inline constexpr int meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE = 6 + 1;
const ::std::string& meshData_proto_RENDER_MODE_Name(meshData_proto_RENDER_MODE value);
template <typename T>
const ::std::string& meshData_proto_RENDER_MODE_Name(T value) {
  static_assert(::std::is_same<T, meshData_proto_RENDER_MODE>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RENDER_MODE_Name().");
  return meshData_proto_RENDER_MODE_Name(static_cast<meshData_proto_RENDER_MODE>(value));
}
bool meshData_proto_RENDER_MODE_Parse(
    ::absl::string_view name, meshData_proto_RENDER_MODE* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class meshData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:meshData_proto) */ {
 public:
  inline meshData_proto() : meshData_proto(nullptr) {}
  ~meshData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(meshData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(meshData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR meshData_proto(::google::protobuf::internal::ConstantInitialized);

  inline meshData_proto(const meshData_proto& from) : meshData_proto(nullptr, from) {}
  inline meshData_proto(meshData_proto&& from) noexcept
      : meshData_proto(nullptr, ::std::move(from)) {}
  inline meshData_proto& operator=(const meshData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline meshData_proto& operator=(meshData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const meshData_proto& default_instance() {
    return *reinterpret_cast<const meshData_proto*>(
        &_meshData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(meshData_proto& a, meshData_proto& b) { a.Swap(&b); }
  inline void Swap(meshData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(meshData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  meshData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<meshData_proto>(arena);
  }
  void CopyFrom(const meshData_proto& from);
  void MergeFrom(const meshData_proto& from) { meshData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(meshData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "meshData_proto"; }

 protected:
  explicit meshData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  meshData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const meshData_proto& from);
  meshData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, meshData_proto&& from) noexcept
      : meshData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using RENDER_MODE = meshData_proto_RENDER_MODE;
  static constexpr RENDER_MODE MODE_POINTS = meshData_proto_RENDER_MODE_MODE_POINTS;
  static constexpr RENDER_MODE MODE_LINE = meshData_proto_RENDER_MODE_MODE_LINE;
  static constexpr RENDER_MODE MODE_LINE_LOOP = meshData_proto_RENDER_MODE_MODE_LINE_LOOP;
  static constexpr RENDER_MODE MODE_LINE_STRIP = meshData_proto_RENDER_MODE_MODE_LINE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLES = meshData_proto_RENDER_MODE_MODE_TRIANGLES;
  static constexpr RENDER_MODE MODE_TRIANGLE_STRIP = meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLE_FAN = meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN;
  static inline bool RENDER_MODE_IsValid(int value) {
    return meshData_proto_RENDER_MODE_IsValid(value);
  }
  static constexpr RENDER_MODE RENDER_MODE_MIN = meshData_proto_RENDER_MODE_RENDER_MODE_MIN;
  static constexpr RENDER_MODE RENDER_MODE_MAX = meshData_proto_RENDER_MODE_RENDER_MODE_MAX;
  static constexpr int RENDER_MODE_ARRAYSIZE = meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& RENDER_MODE_Name(T value) {
    return meshData_proto_RENDER_MODE_Name(value);
  }
  static inline bool RENDER_MODE_Parse(
      ::absl::string_view name, RENDER_MODE* PROTOBUF_NONNULL value) {
    return meshData_proto_RENDER_MODE_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPVersionFieldNumber = 1,
    kPMeshNameFieldNumber = 2,
    kVboVertFieldNumber = 6,
    kVboNormFieldNumber = 7,
    kVboUvFieldNumber = 8,
    kVboIndexFieldNumber = 9,
    kVboColorFieldNumber = 10,
    kModeFieldNumber = 3,
    kTriCountFieldNumber = 4,
    kVertCountFieldNumber = 5,
  };
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const ::std::string& pversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pversion();
  void set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pversion();

  public:
  // optional bytes pMeshName = 2;
  bool has_pmeshname() const;
  void clear_pmeshname() ;
  const ::std::string& pmeshname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pmeshname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pmeshname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pmeshname();
  void set_allocated_pmeshname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pmeshname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pmeshname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pmeshname();

  public:
  // optional .vboData_proto vbo_vert = 6;
  bool has_vbo_vert() const;
  void clear_vbo_vert() ;
  const ::vboData_proto& vbo_vert() const;
  [[nodiscard]] ::vboData_proto* PROTOBUF_NULLABLE release_vbo_vert();
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_vert();
  void set_allocated_vbo_vert(::vboData_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vbo_vert(::vboData_proto* PROTOBUF_NULLABLE value);
  ::vboData_proto* PROTOBUF_NULLABLE unsafe_arena_release_vbo_vert();

  private:
  const ::vboData_proto& _internal_vbo_vert() const;
  ::vboData_proto* PROTOBUF_NONNULL _internal_mutable_vbo_vert();

  public:
  // optional .vboData_proto vbo_norm = 7;
  bool has_vbo_norm() const;
  void clear_vbo_norm() ;
  const ::vboData_proto& vbo_norm() const;
  [[nodiscard]] ::vboData_proto* PROTOBUF_NULLABLE release_vbo_norm();
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_norm();
  void set_allocated_vbo_norm(::vboData_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vbo_norm(::vboData_proto* PROTOBUF_NULLABLE value);
  ::vboData_proto* PROTOBUF_NULLABLE unsafe_arena_release_vbo_norm();

  private:
  const ::vboData_proto& _internal_vbo_norm() const;
  ::vboData_proto* PROTOBUF_NONNULL _internal_mutable_vbo_norm();

  public:
  // optional .vboData_proto vbo_uv = 8;
  bool has_vbo_uv() const;
  void clear_vbo_uv() ;
  const ::vboData_proto& vbo_uv() const;
  [[nodiscard]] ::vboData_proto* PROTOBUF_NULLABLE release_vbo_uv();
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_uv();
  void set_allocated_vbo_uv(::vboData_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vbo_uv(::vboData_proto* PROTOBUF_NULLABLE value);
  ::vboData_proto* PROTOBUF_NULLABLE unsafe_arena_release_vbo_uv();

  private:
  const ::vboData_proto& _internal_vbo_uv() const;
  ::vboData_proto* PROTOBUF_NONNULL _internal_mutable_vbo_uv();

  public:
  // optional .vboData_proto vbo_index = 9;
  bool has_vbo_index() const;
  void clear_vbo_index() ;
  const ::vboData_proto& vbo_index() const;
  [[nodiscard]] ::vboData_proto* PROTOBUF_NULLABLE release_vbo_index();
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_index();
  void set_allocated_vbo_index(::vboData_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vbo_index(::vboData_proto* PROTOBUF_NULLABLE value);
  ::vboData_proto* PROTOBUF_NULLABLE unsafe_arena_release_vbo_index();

  private:
  const ::vboData_proto& _internal_vbo_index() const;
  ::vboData_proto* PROTOBUF_NONNULL _internal_mutable_vbo_index();

  public:
  // optional .vboData_proto vbo_color = 10;
  bool has_vbo_color() const;
  void clear_vbo_color() ;
  const ::vboData_proto& vbo_color() const;
  [[nodiscard]] ::vboData_proto* PROTOBUF_NULLABLE release_vbo_color();
  ::vboData_proto* PROTOBUF_NONNULL mutable_vbo_color();
  void set_allocated_vbo_color(::vboData_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vbo_color(::vboData_proto* PROTOBUF_NULLABLE value);
  ::vboData_proto* PROTOBUF_NULLABLE unsafe_arena_release_vbo_color();

  private:
  const ::vboData_proto& _internal_vbo_color() const;
  ::vboData_proto* PROTOBUF_NONNULL _internal_mutable_vbo_color();

  public:
  // optional .meshData_proto.RENDER_MODE mode = 3;
  bool has_mode() const;
  void clear_mode() ;
  ::meshData_proto_RENDER_MODE mode() const;
  void set_mode(::meshData_proto_RENDER_MODE value);

  private:
  ::meshData_proto_RENDER_MODE _internal_mode() const;
  void _internal_set_mode(::meshData_proto_RENDER_MODE value);

  public:
  // optional uint32 triCount = 4;
  bool has_tricount() const;
  void clear_tricount() ;
  ::uint32_t tricount() const;
  void set_tricount(::uint32_t value);

  private:
  ::uint32_t _internal_tricount() const;
  void _internal_set_tricount(::uint32_t value);

  public:
  // optional uint32 vertCount = 5;
  bool has_vertcount() const;
  void clear_vertcount() ;
  ::uint32_t vertcount() const;
  void set_vertcount(::uint32_t value);

  private:
  ::uint32_t _internal_vertcount() const;
  void _internal_set_vertcount(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:meshData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   5, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const meshData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::google::protobuf::internal::ArenaStringPtr pmeshname_;
    ::vboData_proto* PROTOBUF_NULLABLE vbo_vert_;
    ::vboData_proto* PROTOBUF_NULLABLE vbo_norm_;
    ::vboData_proto* PROTOBUF_NULLABLE vbo_uv_;
    ::vboData_proto* PROTOBUF_NULLABLE vbo_index_;
    ::vboData_proto* PROTOBUF_NULLABLE vbo_color_;
    int mode_;
    ::uint32_t tricount_;
    ::uint32_t vertcount_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meshData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> meshData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// meshData_proto

// optional bytes pVersion = 1;
inline bool meshData_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void meshData_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& meshData_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void meshData_proto::set_pversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:meshData_proto.pVersion)
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::mutable_pversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:meshData_proto.pVersion)
  return _s;
}
inline const ::std::string& meshData_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void meshData_proto::_internal_set_pversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE meshData_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pversion_.Set("", GetArena());
  }
  return released;
}
inline void meshData_proto::set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pversion_.IsDefault()) {
    _impl_.pversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.pVersion)
}

// optional bytes pMeshName = 2;
inline bool meshData_proto::has_pmeshname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void meshData_proto::clear_pmeshname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pmeshname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& meshData_proto::pmeshname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.pMeshName)
  return _internal_pmeshname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void meshData_proto::set_pmeshname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.pmeshname_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:meshData_proto.pMeshName)
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::mutable_pmeshname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pmeshname();
  // @@protoc_insertion_point(field_mutable:meshData_proto.pMeshName)
  return _s;
}
inline const ::std::string& meshData_proto::_internal_pmeshname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pmeshname_.Get();
}
inline void meshData_proto::_internal_set_pmeshname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.pmeshname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL meshData_proto::_internal_mutable_pmeshname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.pmeshname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE meshData_proto::release_pmeshname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.pMeshName)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.pmeshname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pmeshname_.Set("", GetArena());
  }
  return released;
}
inline void meshData_proto::set_allocated_pmeshname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.pmeshname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pmeshname_.IsDefault()) {
    _impl_.pmeshname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.pMeshName)
}

// optional .meshData_proto.RENDER_MODE mode = 3;
inline bool meshData_proto::has_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080U) != 0;
  return value;
}
inline void meshData_proto::clear_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080U;
}
inline ::meshData_proto_RENDER_MODE meshData_proto::mode() const {
  // @@protoc_insertion_point(field_get:meshData_proto.mode)
  return _internal_mode();
}
inline void meshData_proto::set_mode(::meshData_proto_RENDER_MODE value) {
  _internal_set_mode(value);
  _impl_._has_bits_[0] |= 0x00000080U;
  // @@protoc_insertion_point(field_set:meshData_proto.mode)
}
inline ::meshData_proto_RENDER_MODE meshData_proto::_internal_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::meshData_proto_RENDER_MODE>(_impl_.mode_);
}
inline void meshData_proto::_internal_set_mode(::meshData_proto_RENDER_MODE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_ = value;
}

// optional uint32 triCount = 4;
inline bool meshData_proto::has_tricount() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100U) != 0;
  return value;
}
inline void meshData_proto::clear_tricount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tricount_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000100U;
}
inline ::uint32_t meshData_proto::tricount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.triCount)
  return _internal_tricount();
}
inline void meshData_proto::set_tricount(::uint32_t value) {
  _internal_set_tricount(value);
  _impl_._has_bits_[0] |= 0x00000100U;
  // @@protoc_insertion_point(field_set:meshData_proto.triCount)
}
inline ::uint32_t meshData_proto::_internal_tricount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tricount_;
}
inline void meshData_proto::_internal_set_tricount(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tricount_ = value;
}

// optional uint32 vertCount = 5;
inline bool meshData_proto::has_vertcount() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200U) != 0;
  return value;
}
inline void meshData_proto::clear_vertcount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vertcount_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000200U;
}
inline ::uint32_t meshData_proto::vertcount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vertCount)
  return _internal_vertcount();
}
inline void meshData_proto::set_vertcount(::uint32_t value) {
  _internal_set_vertcount(value);
  _impl_._has_bits_[0] |= 0x00000200U;
  // @@protoc_insertion_point(field_set:meshData_proto.vertCount)
}
inline ::uint32_t meshData_proto::_internal_vertcount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vertcount_;
}
inline void meshData_proto::_internal_set_vertcount(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vertcount_ = value;
}

// optional .vboData_proto vbo_vert = 6;
inline bool meshData_proto::has_vbo_vert() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vbo_vert_ != nullptr);
  return value;
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_vert() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::vboData_proto* p = _impl_.vbo_vert_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_vert() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_vert)
  return _internal_vbo_vert();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_vert(
    ::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_vert_);
  }
  _impl_.vbo_vert_ = reinterpret_cast<::vboData_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_vert)
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::release_vbo_vert() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004U;
  ::vboData_proto* released = _impl_.vbo_vert_;
  _impl_.vbo_vert_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::unsafe_arena_release_vbo_vert() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_vert)

  _impl_._has_bits_[0] &= ~0x00000004U;
  ::vboData_proto* temp = _impl_.vbo_vert_;
  _impl_.vbo_vert_ = nullptr;
  return temp;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::_internal_mutable_vbo_vert() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_vert_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::vboData_proto>(GetArena());
    _impl_.vbo_vert_ = reinterpret_cast<::vboData_proto*>(p);
  }
  return _impl_.vbo_vert_;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_vert()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004U;
  ::vboData_proto* _msg = _internal_mutable_vbo_vert();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_vert)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_vert(::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_vert_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }

  _impl_.vbo_vert_ = reinterpret_cast<::vboData_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_vert)
}

// optional .vboData_proto vbo_norm = 7;
inline bool meshData_proto::has_vbo_norm() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vbo_norm_ != nullptr);
  return value;
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_norm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::vboData_proto* p = _impl_.vbo_norm_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_norm() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_norm)
  return _internal_vbo_norm();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_norm(
    ::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_norm_);
  }
  _impl_.vbo_norm_ = reinterpret_cast<::vboData_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_norm)
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::release_vbo_norm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008U;
  ::vboData_proto* released = _impl_.vbo_norm_;
  _impl_.vbo_norm_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::unsafe_arena_release_vbo_norm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_norm)

  _impl_._has_bits_[0] &= ~0x00000008U;
  ::vboData_proto* temp = _impl_.vbo_norm_;
  _impl_.vbo_norm_ = nullptr;
  return temp;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::_internal_mutable_vbo_norm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_norm_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::vboData_proto>(GetArena());
    _impl_.vbo_norm_ = reinterpret_cast<::vboData_proto*>(p);
  }
  return _impl_.vbo_norm_;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_norm()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008U;
  ::vboData_proto* _msg = _internal_mutable_vbo_norm();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_norm)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_norm(::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_norm_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008U;
  }

  _impl_.vbo_norm_ = reinterpret_cast<::vboData_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_norm)
}

// optional .vboData_proto vbo_uv = 8;
inline bool meshData_proto::has_vbo_uv() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vbo_uv_ != nullptr);
  return value;
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_uv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::vboData_proto* p = _impl_.vbo_uv_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_uv() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_uv)
  return _internal_vbo_uv();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_uv(
    ::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_uv_);
  }
  _impl_.vbo_uv_ = reinterpret_cast<::vboData_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_uv)
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::release_vbo_uv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010U;
  ::vboData_proto* released = _impl_.vbo_uv_;
  _impl_.vbo_uv_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::unsafe_arena_release_vbo_uv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_uv)

  _impl_._has_bits_[0] &= ~0x00000010U;
  ::vboData_proto* temp = _impl_.vbo_uv_;
  _impl_.vbo_uv_ = nullptr;
  return temp;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::_internal_mutable_vbo_uv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_uv_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::vboData_proto>(GetArena());
    _impl_.vbo_uv_ = reinterpret_cast<::vboData_proto*>(p);
  }
  return _impl_.vbo_uv_;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_uv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010U;
  ::vboData_proto* _msg = _internal_mutable_vbo_uv();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_uv)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_uv(::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_uv_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010U;
  }

  _impl_.vbo_uv_ = reinterpret_cast<::vboData_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_uv)
}

// optional .vboData_proto vbo_index = 9;
inline bool meshData_proto::has_vbo_index() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vbo_index_ != nullptr);
  return value;
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::vboData_proto* p = _impl_.vbo_index_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_index() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_index)
  return _internal_vbo_index();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_index(
    ::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_index_);
  }
  _impl_.vbo_index_ = reinterpret_cast<::vboData_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_index)
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::release_vbo_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000020U;
  ::vboData_proto* released = _impl_.vbo_index_;
  _impl_.vbo_index_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::unsafe_arena_release_vbo_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_index)

  _impl_._has_bits_[0] &= ~0x00000020U;
  ::vboData_proto* temp = _impl_.vbo_index_;
  _impl_.vbo_index_ = nullptr;
  return temp;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::_internal_mutable_vbo_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_index_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::vboData_proto>(GetArena());
    _impl_.vbo_index_ = reinterpret_cast<::vboData_proto*>(p);
  }
  return _impl_.vbo_index_;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_index()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000020U;
  ::vboData_proto* _msg = _internal_mutable_vbo_index();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_index)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_index(::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_index_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000020U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020U;
  }

  _impl_.vbo_index_ = reinterpret_cast<::vboData_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_index)
}

// optional .vboData_proto vbo_color = 10;
inline bool meshData_proto::has_vbo_color() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vbo_color_ != nullptr);
  return value;
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::vboData_proto* p = _impl_.vbo_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_color)
  return _internal_vbo_color();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_color(
    ::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_color_);
  }
  _impl_.vbo_color_ = reinterpret_cast<::vboData_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_color)
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::release_vbo_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000040U;
  ::vboData_proto* released = _impl_.vbo_color_;
  _impl_.vbo_color_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::vboData_proto* PROTOBUF_NULLABLE meshData_proto::unsafe_arena_release_vbo_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_color)

  _impl_._has_bits_[0] &= ~0x00000040U;
  ::vboData_proto* temp = _impl_.vbo_color_;
  _impl_.vbo_color_ = nullptr;
  return temp;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::_internal_mutable_vbo_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_color_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::vboData_proto>(GetArena());
    _impl_.vbo_color_ = reinterpret_cast<::vboData_proto*>(p);
  }
  return _impl_.vbo_color_;
}
inline ::vboData_proto* PROTOBUF_NONNULL meshData_proto::mutable_vbo_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000040U;
  ::vboData_proto* _msg = _internal_mutable_vbo_color();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_color)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_color(::vboData_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vbo_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000040U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040U;
  }

  _impl_.vbo_color_ = reinterpret_cast<::vboData_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_color)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::meshData_proto_RENDER_MODE> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // meshData_2eproto_2epb_2eh
