// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meshData.proto
// Protobuf C++ Version: 6.32.0-dev

#include "meshData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr meshData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pmeshname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        vbo_vert_{nullptr},
        vbo_norm_{nullptr},
        vbo_uv_{nullptr},
        vbo_index_{nullptr},
        vbo_color_{nullptr},
        mode_{static_cast< ::meshData_proto_RENDER_MODE >(0)},
        tricount_{0u},
        vertcount_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR meshData_proto::meshData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(meshData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct meshData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR meshData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~meshData_protoDefaultTypeInternal() {}
  union {
    meshData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
PROTOBUF_CONSTINIT const uint32_t meshData_proto_RENDER_MODE_internal_data_[] = {
    458752u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    meshData_proto_RENDER_MODE_strings[7] = {};

static const char meshData_proto_RENDER_MODE_names[] = {
    "MODE_LINE"
    "MODE_LINE_LOOP"
    "MODE_LINE_STRIP"
    "MODE_POINTS"
    "MODE_TRIANGLES"
    "MODE_TRIANGLE_FAN"
    "MODE_TRIANGLE_STRIP"
};

static const ::google::protobuf::internal::EnumEntry meshData_proto_RENDER_MODE_entries[] = {
    {{&meshData_proto_RENDER_MODE_names[0], 9}, 1},
    {{&meshData_proto_RENDER_MODE_names[9], 14}, 2},
    {{&meshData_proto_RENDER_MODE_names[23], 15}, 3},
    {{&meshData_proto_RENDER_MODE_names[38], 11}, 0},
    {{&meshData_proto_RENDER_MODE_names[49], 14}, 4},
    {{&meshData_proto_RENDER_MODE_names[63], 17}, 6},
    {{&meshData_proto_RENDER_MODE_names[80], 19}, 5},
};

static const int meshData_proto_RENDER_MODE_entries_by_number[] = {
    3,  // 0 -> MODE_POINTS
    0,  // 1 -> MODE_LINE
    1,  // 2 -> MODE_LINE_LOOP
    2,  // 3 -> MODE_LINE_STRIP
    4,  // 4 -> MODE_TRIANGLES
    6,  // 5 -> MODE_TRIANGLE_STRIP
    5,  // 6 -> MODE_TRIANGLE_FAN
};

const ::std::string& meshData_proto_RENDER_MODE_Name(meshData_proto_RENDER_MODE value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      meshData_proto_RENDER_MODE_entries, meshData_proto_RENDER_MODE_entries_by_number, 7,
      meshData_proto_RENDER_MODE_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(meshData_proto_RENDER_MODE_entries,
                                  meshData_proto_RENDER_MODE_entries_by_number,
                                  7, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : meshData_proto_RENDER_MODE_strings[idx].get();
}

bool meshData_proto_RENDER_MODE_Parse(::absl::string_view name, meshData_proto_RENDER_MODE* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      meshData_proto_RENDER_MODE_entries, 7, name, &int_value);
  if (success) {
    *value = static_cast<meshData_proto_RENDER_MODE>(int_value);
  }
  return success;
}
// ===================================================================

class meshData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<meshData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_._has_bits_);
};

void meshData_proto::clear_vbo_vert() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_vert_ != nullptr) _impl_.vbo_vert_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
void meshData_proto::clear_vbo_norm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_norm_ != nullptr) _impl_.vbo_norm_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008U;
}
void meshData_proto::clear_vbo_uv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_uv_ != nullptr) _impl_.vbo_uv_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010U;
}
void meshData_proto::clear_vbo_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_index_ != nullptr) _impl_.vbo_index_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020U;
}
void meshData_proto::clear_vbo_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vbo_color_ != nullptr) _impl_.vbo_color_->Clear();
  _impl_._has_bits_[0] &= ~0x00000040U;
}
meshData_proto::meshData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, meshData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:meshData_proto)
}
PROTOBUF_NDEBUG_INLINE meshData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::meshData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pversion_(arena, from.pversion_),
        pmeshname_(arena, from.pmeshname_) {}

meshData_proto::meshData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const meshData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, meshData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  meshData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.vbo_vert_ = ((cached_has_bits & 0x00000004U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_vert_)
                : nullptr;
  _impl_.vbo_norm_ = ((cached_has_bits & 0x00000008U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_norm_)
                : nullptr;
  _impl_.vbo_uv_ = ((cached_has_bits & 0x00000010U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_uv_)
                : nullptr;
  _impl_.vbo_index_ = ((cached_has_bits & 0x00000020U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_index_)
                : nullptr;
  _impl_.vbo_color_ = ((cached_has_bits & 0x00000040U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_color_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, mode_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, mode_),
           offsetof(Impl_, vertcount_) -
               offsetof(Impl_, mode_) +
               sizeof(Impl_::vertcount_));

  // @@protoc_insertion_point(copy_constructor:meshData_proto)
}
PROTOBUF_NDEBUG_INLINE meshData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pversion_(arena),
        pmeshname_(arena) {}

inline void meshData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, vbo_vert_),
           0,
           offsetof(Impl_, vertcount_) -
               offsetof(Impl_, vbo_vert_) +
               sizeof(Impl_::vertcount_));
}
meshData_proto::~meshData_proto() {
  // @@protoc_insertion_point(destructor:meshData_proto)
  SharedDtor(*this);
}
inline void meshData_proto::SharedDtor(MessageLite& self) {
  meshData_proto& this_ = static_cast<meshData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pversion_.Destroy();
  this_._impl_.pmeshname_.Destroy();
  delete this_._impl_.vbo_vert_;
  delete this_._impl_.vbo_norm_;
  delete this_._impl_.vbo_uv_;
  delete this_._impl_.vbo_index_;
  delete this_._impl_.vbo_color_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL meshData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) meshData_proto(arena);
}
constexpr auto meshData_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(meshData_proto),
                                            alignof(meshData_proto));
}
constexpr auto meshData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_meshData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &meshData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<meshData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &meshData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<meshData_proto>(), &meshData_proto::ByteSizeLong,
              &meshData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_._cached_size_),
          true,
      },
      "meshData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> meshData_proto_class_data_ =
    meshData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
meshData_proto::GetClassData() const {
  return meshData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 5, 0, 2>
meshData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    meshData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::meshData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bytes pVersion = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pversion_)}},
    // optional bytes pMeshName = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pmeshname_)}},
    // optional .meshData_proto.RENDER_MODE mode = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 7, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.mode_)}},
    // optional uint32 triCount = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 8, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.tricount_)}},
    // optional uint32 vertCount = 5;
    {::_pbi::TcParser::FastV32S1,
     {40, 9, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vertcount_)}},
    // optional .vboData_proto vbo_vert = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 2, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_vert_)}},
    // optional .vboData_proto vbo_norm = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 3, 1, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_norm_)}},
    // optional .vboData_proto vbo_uv = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 4, 2, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_uv_)}},
    // optional .vboData_proto vbo_index = 9;
    {::_pbi::TcParser::FastMtS1,
     {74, 5, 3, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_index_)}},
    // optional .vboData_proto vbo_color = 10;
    {::_pbi::TcParser::FastMtS1,
     {82, 6, 4, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_color_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes pVersion = 1;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pversion_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes pMeshName = 2;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pmeshname_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional .meshData_proto.RENDER_MODE mode = 3;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.mode_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional uint32 triCount = 4;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.tricount_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 vertCount = 5;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vertcount_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .vboData_proto vbo_vert = 6;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_vert_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .vboData_proto vbo_norm = 7;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_norm_), _Internal::kHasBitsOffset + 3, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .vboData_proto vbo_uv = 8;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_uv_), _Internal::kHasBitsOffset + 4, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .vboData_proto vbo_index = 9;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_index_), _Internal::kHasBitsOffset + 5, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .vboData_proto vbo_color = 10;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_color_), _Internal::kHasBitsOffset + 6, 4, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void meshData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:meshData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000007fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.pversion_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.pmeshname_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      ABSL_DCHECK(_impl_.vbo_vert_ != nullptr);
      _impl_.vbo_vert_->Clear();
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      ABSL_DCHECK(_impl_.vbo_norm_ != nullptr);
      _impl_.vbo_norm_->Clear();
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      ABSL_DCHECK(_impl_.vbo_uv_ != nullptr);
      _impl_.vbo_uv_->Clear();
    }
    if ((cached_has_bits & 0x00000020U) != 0) {
      ABSL_DCHECK(_impl_.vbo_index_ != nullptr);
      _impl_.vbo_index_->Clear();
    }
    if ((cached_has_bits & 0x00000040U) != 0) {
      ABSL_DCHECK(_impl_.vbo_color_ != nullptr);
      _impl_.vbo_color_->Clear();
    }
  }
  _impl_.mode_ = 0;
  if ((cached_has_bits & 0x00000300U) != 0) {
    ::memset(&_impl_.tricount_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.vertcount_) -
        reinterpret_cast<char*>(&_impl_.tricount_)) + sizeof(_impl_.vertcount_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL meshData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const meshData_proto& this_ = static_cast<const meshData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL meshData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const meshData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:meshData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes pVersion = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_pversion();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional bytes pMeshName = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    const ::std::string& _s = this_._internal_pmeshname();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional .meshData_proto.RENDER_MODE mode = 3;
  if ((cached_has_bits & 0x00000080U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this_._internal_mode(), target);
  }

  // optional uint32 triCount = 4;
  if ((cached_has_bits & 0x00000100U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_tricount(), target);
  }

  // optional uint32 vertCount = 5;
  if ((cached_has_bits & 0x00000200U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_vertcount(), target);
  }

  // optional .vboData_proto vbo_vert = 6;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.vbo_vert_, this_._impl_.vbo_vert_->GetCachedSize(), target,
        stream);
  }

  // optional .vboData_proto vbo_norm = 7;
  if ((cached_has_bits & 0x00000008U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.vbo_norm_, this_._impl_.vbo_norm_->GetCachedSize(), target,
        stream);
  }

  // optional .vboData_proto vbo_uv = 8;
  if ((cached_has_bits & 0x00000010U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *this_._impl_.vbo_uv_, this_._impl_.vbo_uv_->GetCachedSize(), target,
        stream);
  }

  // optional .vboData_proto vbo_index = 9;
  if ((cached_has_bits & 0x00000020U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        9, *this_._impl_.vbo_index_, this_._impl_.vbo_index_->GetCachedSize(), target,
        stream);
  }

  // optional .vboData_proto vbo_color = 10;
  if ((cached_has_bits & 0x00000040U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        10, *this_._impl_.vbo_color_, this_._impl_.vbo_color_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meshData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t meshData_proto::ByteSizeLong(const MessageLite& base) {
  const meshData_proto& this_ = static_cast<const meshData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t meshData_proto::ByteSizeLong() const {
  const meshData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:meshData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    // optional bytes pVersion = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_pversion());
    }
    // optional bytes pMeshName = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_pmeshname());
    }
    // optional .vboData_proto vbo_vert = 6;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.vbo_vert_);
    }
    // optional .vboData_proto vbo_norm = 7;
    if ((cached_has_bits & 0x00000008U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.vbo_norm_);
    }
    // optional .vboData_proto vbo_uv = 8;
    if ((cached_has_bits & 0x00000010U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.vbo_uv_);
    }
    // optional .vboData_proto vbo_index = 9;
    if ((cached_has_bits & 0x00000020U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.vbo_index_);
    }
    // optional .vboData_proto vbo_color = 10;
    if ((cached_has_bits & 0x00000040U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.vbo_color_);
    }
    // optional .meshData_proto.RENDER_MODE mode = 3;
    if ((cached_has_bits & 0x00000080U) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_mode());
    }
  }
  if ((cached_has_bits & 0x00000300U) != 0) {
    // optional uint32 triCount = 4;
    if ((cached_has_bits & 0x00000100U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_tricount());
    }
    // optional uint32 vertCount = 5;
    if ((cached_has_bits & 0x00000200U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_vertcount());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void meshData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<meshData_proto*>(&to_msg);
  auto& from = static_cast<const meshData_proto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:meshData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_pversion(from._internal_pversion());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_internal_set_pmeshname(from._internal_pmeshname());
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      ABSL_DCHECK(from._impl_.vbo_vert_ != nullptr);
      if (_this->_impl_.vbo_vert_ == nullptr) {
        _this->_impl_.vbo_vert_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_vert_);
      } else {
        _this->_impl_.vbo_vert_->MergeFrom(*from._impl_.vbo_vert_);
      }
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      ABSL_DCHECK(from._impl_.vbo_norm_ != nullptr);
      if (_this->_impl_.vbo_norm_ == nullptr) {
        _this->_impl_.vbo_norm_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_norm_);
      } else {
        _this->_impl_.vbo_norm_->MergeFrom(*from._impl_.vbo_norm_);
      }
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      ABSL_DCHECK(from._impl_.vbo_uv_ != nullptr);
      if (_this->_impl_.vbo_uv_ == nullptr) {
        _this->_impl_.vbo_uv_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_uv_);
      } else {
        _this->_impl_.vbo_uv_->MergeFrom(*from._impl_.vbo_uv_);
      }
    }
    if ((cached_has_bits & 0x00000020U) != 0) {
      ABSL_DCHECK(from._impl_.vbo_index_ != nullptr);
      if (_this->_impl_.vbo_index_ == nullptr) {
        _this->_impl_.vbo_index_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_index_);
      } else {
        _this->_impl_.vbo_index_->MergeFrom(*from._impl_.vbo_index_);
      }
    }
    if ((cached_has_bits & 0x00000040U) != 0) {
      ABSL_DCHECK(from._impl_.vbo_color_ != nullptr);
      if (_this->_impl_.vbo_color_ == nullptr) {
        _this->_impl_.vbo_color_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.vbo_color_);
      } else {
        _this->_impl_.vbo_color_->MergeFrom(*from._impl_.vbo_color_);
      }
    }
    if ((cached_has_bits & 0x00000080U) != 0) {
      _this->_impl_.mode_ = from._impl_.mode_;
    }
  }
  if ((cached_has_bits & 0x00000300U) != 0) {
    if ((cached_has_bits & 0x00000100U) != 0) {
      _this->_impl_.tricount_ = from._impl_.tricount_;
    }
    if ((cached_has_bits & 0x00000200U) != 0) {
      _this->_impl_.vertcount_ = from._impl_.vertcount_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void meshData_proto::CopyFrom(const meshData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meshData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void meshData_proto::InternalSwap(meshData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pversion_, &other->_impl_.pversion_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pmeshname_, &other->_impl_.pmeshname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vertcount_)
      + sizeof(meshData_proto::_impl_.vertcount_)
      - PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_vert_)>(
          reinterpret_cast<char*>(&_impl_.vbo_vert_),
          reinterpret_cast<char*>(&other->_impl_.vbo_vert_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
