// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meshData.proto
// Protobuf C++ Version: 6.32.0-dev

#include "meshData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr meshData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pmeshname_{},
        mode_{},
        _mode_cached_byte_size_{0},
        tricount_{},
        _tricount_cached_byte_size_{0},
        vertcount_{},
        _vertcount_cached_byte_size_{0},
        vbo_vert_{},
        vbo_norm_{},
        vbo_uv_{},
        vbo_index_{},
        vbo_color_{},
        pversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        meshcount_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR meshData_proto::meshData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(meshData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct meshData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR meshData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~meshData_protoDefaultTypeInternal() {}
  union {
    meshData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
PROTOBUF_CONSTINIT const uint32_t meshData_proto_RENDER_MODE_internal_data_[] = {
    458752u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    meshData_proto_RENDER_MODE_strings[7] = {};

static const char meshData_proto_RENDER_MODE_names[] = {
    "MODE_LINE"
    "MODE_LINE_LOOP"
    "MODE_LINE_STRIP"
    "MODE_POINTS"
    "MODE_TRIANGLES"
    "MODE_TRIANGLE_FAN"
    "MODE_TRIANGLE_STRIP"
};

static const ::google::protobuf::internal::EnumEntry meshData_proto_RENDER_MODE_entries[] = {
    {{&meshData_proto_RENDER_MODE_names[0], 9}, 1},
    {{&meshData_proto_RENDER_MODE_names[9], 14}, 2},
    {{&meshData_proto_RENDER_MODE_names[23], 15}, 3},
    {{&meshData_proto_RENDER_MODE_names[38], 11}, 0},
    {{&meshData_proto_RENDER_MODE_names[49], 14}, 4},
    {{&meshData_proto_RENDER_MODE_names[63], 17}, 6},
    {{&meshData_proto_RENDER_MODE_names[80], 19}, 5},
};

static const int meshData_proto_RENDER_MODE_entries_by_number[] = {
    3,  // 0 -> MODE_POINTS
    0,  // 1 -> MODE_LINE
    1,  // 2 -> MODE_LINE_LOOP
    2,  // 3 -> MODE_LINE_STRIP
    4,  // 4 -> MODE_TRIANGLES
    6,  // 5 -> MODE_TRIANGLE_STRIP
    5,  // 6 -> MODE_TRIANGLE_FAN
};

const ::std::string& meshData_proto_RENDER_MODE_Name(meshData_proto_RENDER_MODE value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      meshData_proto_RENDER_MODE_entries, meshData_proto_RENDER_MODE_entries_by_number, 7,
      meshData_proto_RENDER_MODE_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(meshData_proto_RENDER_MODE_entries,
                                  meshData_proto_RENDER_MODE_entries_by_number,
                                  7, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : meshData_proto_RENDER_MODE_strings[idx].get();
}

bool meshData_proto_RENDER_MODE_Parse(::absl::string_view name, meshData_proto_RENDER_MODE* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      meshData_proto_RENDER_MODE_entries, 7, name, &int_value);
  if (success) {
    *value = static_cast<meshData_proto_RENDER_MODE>(int_value);
  }
  return success;
}
// ===================================================================

class meshData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<meshData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_._has_bits_);
};

void meshData_proto::clear_vbo_vert() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbo_vert_.Clear();
}
void meshData_proto::clear_vbo_norm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbo_norm_.Clear();
}
void meshData_proto::clear_vbo_uv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbo_uv_.Clear();
}
void meshData_proto::clear_vbo_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbo_index_.Clear();
}
void meshData_proto::clear_vbo_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbo_color_.Clear();
}
meshData_proto::meshData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, meshData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:meshData_proto)
}
PROTOBUF_NDEBUG_INLINE meshData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::meshData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pmeshname_{visibility, arena, from.pmeshname_},
        mode_{visibility, arena, from.mode_},
        _mode_cached_byte_size_{0},
        tricount_{visibility, arena, from.tricount_},
        _tricount_cached_byte_size_{0},
        vertcount_{visibility, arena, from.vertcount_},
        _vertcount_cached_byte_size_{0},
        vbo_vert_{visibility, arena, from.vbo_vert_},
        vbo_norm_{visibility, arena, from.vbo_norm_},
        vbo_uv_{visibility, arena, from.vbo_uv_},
        vbo_index_{visibility, arena, from.vbo_index_},
        vbo_color_{visibility, arena, from.vbo_color_},
        pversion_(arena, from.pversion_) {}

meshData_proto::meshData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const meshData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, meshData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  meshData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.meshcount_ = from._impl_.meshcount_;

  // @@protoc_insertion_point(copy_constructor:meshData_proto)
}
PROTOBUF_NDEBUG_INLINE meshData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pmeshname_{visibility, arena},
        mode_{visibility, arena},
        _mode_cached_byte_size_{0},
        tricount_{visibility, arena},
        _tricount_cached_byte_size_{0},
        vertcount_{visibility, arena},
        _vertcount_cached_byte_size_{0},
        vbo_vert_{visibility, arena},
        vbo_norm_{visibility, arena},
        vbo_uv_{visibility, arena},
        vbo_index_{visibility, arena},
        vbo_color_{visibility, arena},
        pversion_(arena) {}

inline void meshData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.meshcount_ = {};
}
meshData_proto::~meshData_proto() {
  // @@protoc_insertion_point(destructor:meshData_proto)
  SharedDtor(*this);
}
inline void meshData_proto::SharedDtor(MessageLite& self) {
  meshData_proto& this_ = static_cast<meshData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pversion_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL meshData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) meshData_proto(arena);
}
constexpr auto meshData_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pmeshname_) +
          decltype(meshData_proto::_impl_.pmeshname_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.mode_) +
          decltype(meshData_proto::_impl_.mode_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.tricount_) +
          decltype(meshData_proto::_impl_.tricount_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vertcount_) +
          decltype(meshData_proto::_impl_.vertcount_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_vert_) +
          decltype(meshData_proto::_impl_.vbo_vert_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_norm_) +
          decltype(meshData_proto::_impl_.vbo_norm_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_uv_) +
          decltype(meshData_proto::_impl_.vbo_uv_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_index_) +
          decltype(meshData_proto::_impl_.vbo_index_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_color_) +
          decltype(meshData_proto::_impl_.vbo_color_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(meshData_proto), alignof(meshData_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&meshData_proto::PlacementNew_,
                                 sizeof(meshData_proto),
                                 alignof(meshData_proto));
  }
}
constexpr auto meshData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_meshData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &meshData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<meshData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &meshData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<meshData_proto>(), &meshData_proto::ByteSizeLong,
              &meshData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_._cached_size_),
          true,
      },
      "meshData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> meshData_proto_class_data_ =
    meshData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
meshData_proto::GetClassData() const {
  return meshData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 5, 0, 2>
meshData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    meshData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::meshData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bytes pVersion = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pversion_)}},
    // optional uint32 meshCount = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.meshcount_)}},
    // repeated bytes pMeshName = 3;
    {::_pbi::TcParser::FastBR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pmeshname_)}},
    // repeated .meshData_proto.RENDER_MODE mode = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.mode_)}},
    // repeated uint32 triCount = 5;
    {::_pbi::TcParser::FastV32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.tricount_)}},
    // repeated uint32 vertCount = 6;
    {::_pbi::TcParser::FastV32P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vertcount_)}},
    // repeated .vboData_proto vbo_vert = 7;
    {::_pbi::TcParser::FastMtR1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_vert_)}},
    // repeated .vboData_proto vbo_norm = 8;
    {::_pbi::TcParser::FastMtR1,
     {66, 63, 1, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_norm_)}},
    // repeated .vboData_proto vbo_uv = 9;
    {::_pbi::TcParser::FastMtR1,
     {74, 63, 2, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_uv_)}},
    // repeated .vboData_proto vbo_index = 10;
    {::_pbi::TcParser::FastMtR1,
     {82, 63, 3, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_index_)}},
    // repeated .vboData_proto vbo_color = 11;
    {::_pbi::TcParser::FastMtR1,
     {90, 63, 4, PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_color_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes pVersion = 1;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pversion_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 meshCount = 2;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.meshcount_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated bytes pMeshName = 3;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.pmeshname_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated .meshData_proto.RENDER_MODE mode = 4;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.mode_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedOpenEnum)},
    // repeated uint32 triCount = 5;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.tricount_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated uint32 vertCount = 6;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vertcount_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated .vboData_proto vbo_vert = 7;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_vert_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .vboData_proto vbo_norm = 8;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_norm_), -1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .vboData_proto vbo_uv = 9;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_uv_), -1, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .vboData_proto vbo_index = 10;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_index_), -1, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .vboData_proto vbo_color = 11;
    {PROTOBUF_FIELD_OFFSET(meshData_proto, _impl_.vbo_color_), -1, 4, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
      {::_pbi::TcParser::GetTable<::vboData_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void meshData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:meshData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pmeshname_.Clear();
  _impl_.mode_.Clear();
  _impl_.tricount_.Clear();
  _impl_.vertcount_.Clear();
  _impl_.vbo_vert_.Clear();
  _impl_.vbo_norm_.Clear();
  _impl_.vbo_uv_.Clear();
  _impl_.vbo_index_.Clear();
  _impl_.vbo_color_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.pversion_.ClearNonDefaultToEmpty();
  }
  _impl_.meshcount_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL meshData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const meshData_proto& this_ = static_cast<const meshData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL meshData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const meshData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:meshData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes pVersion = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_pversion();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional uint32 meshCount = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_meshcount(), target);
  }

  // repeated bytes pMeshName = 3;
  for (int i = 0, n = this_._internal_pmeshname_size(); i < n; ++i) {
    const auto& s = this_._internal_pmeshname().Get(i);
    target = stream->WriteBytes(3, s, target);
  }

  // repeated .meshData_proto.RENDER_MODE mode = 4;
  {
    ::size_t byte_size = this_._impl_._mode_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          4, this_._internal_mode(), byte_size, target);
    }
  }

  // repeated uint32 triCount = 5;
  {
    int byte_size = this_._impl_._tricount_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          5, this_._internal_tricount(), byte_size, target);
    }
  }

  // repeated uint32 vertCount = 6;
  {
    int byte_size = this_._impl_._vertcount_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          6, this_._internal_vertcount(), byte_size, target);
    }
  }

  // repeated .vboData_proto vbo_vert = 7;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_vbo_vert_size());
       i < n; i++) {
    const auto& repfield = this_._internal_vbo_vert().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            7, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .vboData_proto vbo_norm = 8;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_vbo_norm_size());
       i < n; i++) {
    const auto& repfield = this_._internal_vbo_norm().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            8, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .vboData_proto vbo_uv = 9;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_vbo_uv_size());
       i < n; i++) {
    const auto& repfield = this_._internal_vbo_uv().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            9, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .vboData_proto vbo_index = 10;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_vbo_index_size());
       i < n; i++) {
    const auto& repfield = this_._internal_vbo_index().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            10, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .vboData_proto vbo_color = 11;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_vbo_color_size());
       i < n; i++) {
    const auto& repfield = this_._internal_vbo_color().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            11, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meshData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t meshData_proto::ByteSizeLong(const MessageLite& base) {
  const meshData_proto& this_ = static_cast<const meshData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t meshData_proto::ByteSizeLong() const {
  const meshData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:meshData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated bytes pMeshName = 3;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_pmeshname().size());
      for (int i = 0, n = this_._internal_pmeshname().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_pmeshname().Get(i));
      }
    }
    // repeated .meshData_proto.RENDER_MODE mode = 4;
    {
      total_size += ::_pbi::WireFormatLite::EnumSizeWithPackedTagSize(
          this_._internal_mode(), 1, this_._impl_._mode_cached_byte_size_);
    }
    // repeated uint32 triCount = 5;
    {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_tricount(), 1,
              this_._impl_._tricount_cached_byte_size_);
    }
    // repeated uint32 vertCount = 6;
    {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_vertcount(), 1,
              this_._impl_._vertcount_cached_byte_size_);
    }
    // repeated .vboData_proto vbo_vert = 7;
    {
      total_size += 1UL * this_._internal_vbo_vert_size();
      for (const auto& msg : this_._internal_vbo_vert()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .vboData_proto vbo_norm = 8;
    {
      total_size += 1UL * this_._internal_vbo_norm_size();
      for (const auto& msg : this_._internal_vbo_norm()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .vboData_proto vbo_uv = 9;
    {
      total_size += 1UL * this_._internal_vbo_uv_size();
      for (const auto& msg : this_._internal_vbo_uv()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .vboData_proto vbo_index = 10;
    {
      total_size += 1UL * this_._internal_vbo_index_size();
      for (const auto& msg : this_._internal_vbo_index()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .vboData_proto vbo_color = 11;
    {
      total_size += 1UL * this_._internal_vbo_color_size();
      for (const auto& msg : this_._internal_vbo_color()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // optional bytes pVersion = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_pversion());
    }
    // optional uint32 meshCount = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_meshcount());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void meshData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<meshData_proto*>(&to_msg);
  auto& from = static_cast<const meshData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:meshData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pmeshname()->MergeFrom(from._internal_pmeshname());
  _this->_internal_mutable_mode()->MergeFrom(from._internal_mode());
  _this->_internal_mutable_tricount()->MergeFrom(from._internal_tricount());
  _this->_internal_mutable_vertcount()->MergeFrom(from._internal_vertcount());
  _this->_internal_mutable_vbo_vert()->MergeFrom(
      from._internal_vbo_vert());
  _this->_internal_mutable_vbo_norm()->MergeFrom(
      from._internal_vbo_norm());
  _this->_internal_mutable_vbo_uv()->MergeFrom(
      from._internal_vbo_uv());
  _this->_internal_mutable_vbo_index()->MergeFrom(
      from._internal_vbo_index());
  _this->_internal_mutable_vbo_color()->MergeFrom(
      from._internal_vbo_color());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_pversion(from._internal_pversion());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.meshcount_ = from._impl_.meshcount_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void meshData_proto::CopyFrom(const meshData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meshData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void meshData_proto::InternalSwap(meshData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pmeshname_.InternalSwap(&other->_impl_.pmeshname_);
  _impl_.mode_.InternalSwap(&other->_impl_.mode_);
  _impl_.tricount_.InternalSwap(&other->_impl_.tricount_);
  _impl_.vertcount_.InternalSwap(&other->_impl_.vertcount_);
  _impl_.vbo_vert_.InternalSwap(&other->_impl_.vbo_vert_);
  _impl_.vbo_norm_.InternalSwap(&other->_impl_.vbo_norm_);
  _impl_.vbo_uv_.InternalSwap(&other->_impl_.vbo_uv_);
  _impl_.vbo_index_.InternalSwap(&other->_impl_.vbo_index_);
  _impl_.vbo_color_.InternalSwap(&other->_impl_.vbo_color_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pversion_, &other->_impl_.pversion_, arena);
  swap(_impl_.meshcount_, other->_impl_.meshcount_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
