// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: textureData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef textureData_2eproto_2epb_2eh
#define textureData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_textureData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_textureData_2eproto {
  static const ::uint32_t offsets[];
};
enum textureData_proto_TEXTURE_COMPONENT : int;
extern const uint32_t textureData_proto_TEXTURE_COMPONENT_internal_data_[];
enum textureData_proto_TEXTURE_EFORMAT : int;
extern const uint32_t textureData_proto_TEXTURE_EFORMAT_internal_data_[];
enum textureData_proto_TEXTURE_MAG_FILTER : int;
extern const uint32_t textureData_proto_TEXTURE_MAG_FILTER_internal_data_[];
enum textureData_proto_TEXTURE_MIN_FILTER : int;
extern const uint32_t textureData_proto_TEXTURE_MIN_FILTER_internal_data_[];
enum textureData_proto_TEXTURE_NCOMPONENT : int;
extern const uint32_t textureData_proto_TEXTURE_NCOMPONENT_internal_data_[];
enum textureData_proto_TEXTURE_TYPE : int;
extern const uint32_t textureData_proto_TEXTURE_TYPE_internal_data_[];
enum textureData_proto_TEXTURE_WRAP : int;
extern const uint32_t textureData_proto_TEXTURE_WRAP_internal_data_[];
class textureData_proto;
struct textureData_protoDefaultTypeInternal;
extern textureData_protoDefaultTypeInternal _textureData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<18> textureData_proto_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_COMPONENT_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_COMPONENT>;
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_EFORMAT_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_EFORMAT>;
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_MAG_FILTER_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_MAG_FILTER>;
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_MIN_FILTER_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_MIN_FILTER>;
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_NCOMPONENT_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_NCOMPONENT>;
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_TYPE_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_TYPE>;
template <>
internal::EnumTraitsT<::textureData_proto_TEXTURE_WRAP_internal_data_>
    internal::EnumTraitsImpl::value<::textureData_proto_TEXTURE_WRAP>;
}  // namespace protobuf
}  // namespace google

enum textureData_proto_TEXTURE_EFORMAT : int {
  textureData_proto_TEXTURE_EFORMAT_EFORMAT_BGR = 0,
  textureData_proto_TEXTURE_EFORMAT_EFORMAT_RGB = 1,
  textureData_proto_TEXTURE_EFORMAT_EFORMAT_RGBA = 2,
  textureData_proto_TEXTURE_EFORMAT_textureData_proto_TEXTURE_EFORMAT_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_EFORMAT_textureData_proto_TEXTURE_EFORMAT_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_EFORMAT_internal_data_[];
inline constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto_TEXTURE_EFORMAT_TEXTURE_EFORMAT_MIN =
    static_cast<textureData_proto_TEXTURE_EFORMAT>(0);
inline constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto_TEXTURE_EFORMAT_TEXTURE_EFORMAT_MAX =
    static_cast<textureData_proto_TEXTURE_EFORMAT>(2);
inline bool textureData_proto_TEXTURE_EFORMAT_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int textureData_proto_TEXTURE_EFORMAT_TEXTURE_EFORMAT_ARRAYSIZE = 2 + 1;
const ::std::string& textureData_proto_TEXTURE_EFORMAT_Name(textureData_proto_TEXTURE_EFORMAT value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_EFORMAT_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_EFORMAT>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_EFORMAT_Name().");
  return textureData_proto_TEXTURE_EFORMAT_Name(static_cast<textureData_proto_TEXTURE_EFORMAT>(value));
}
bool textureData_proto_TEXTURE_EFORMAT_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_EFORMAT* PROTOBUF_NONNULL value);
enum textureData_proto_TEXTURE_NCOMPONENT : int {
  textureData_proto_TEXTURE_NCOMPONENT_NCOMPONENT_BGR = 0,
  textureData_proto_TEXTURE_NCOMPONENT_NCOMPONENT_RGB = 1,
  textureData_proto_TEXTURE_NCOMPONENT_NCOMPONENT_RGBA = 2,
  textureData_proto_TEXTURE_NCOMPONENT_textureData_proto_TEXTURE_NCOMPONENT_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_NCOMPONENT_textureData_proto_TEXTURE_NCOMPONENT_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_NCOMPONENT_internal_data_[];
inline constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto_TEXTURE_NCOMPONENT_TEXTURE_NCOMPONENT_MIN =
    static_cast<textureData_proto_TEXTURE_NCOMPONENT>(0);
inline constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto_TEXTURE_NCOMPONENT_TEXTURE_NCOMPONENT_MAX =
    static_cast<textureData_proto_TEXTURE_NCOMPONENT>(2);
inline bool textureData_proto_TEXTURE_NCOMPONENT_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int textureData_proto_TEXTURE_NCOMPONENT_TEXTURE_NCOMPONENT_ARRAYSIZE = 2 + 1;
const ::std::string& textureData_proto_TEXTURE_NCOMPONENT_Name(textureData_proto_TEXTURE_NCOMPONENT value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_NCOMPONENT_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_NCOMPONENT>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_NCOMPONENT_Name().");
  return textureData_proto_TEXTURE_NCOMPONENT_Name(static_cast<textureData_proto_TEXTURE_NCOMPONENT>(value));
}
bool textureData_proto_TEXTURE_NCOMPONENT_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_NCOMPONENT* PROTOBUF_NONNULL value);
enum textureData_proto_TEXTURE_TYPE : int {
  textureData_proto_TEXTURE_TYPE_JPEG = 0,
  textureData_proto_TEXTURE_TYPE_PNG = 1,
  textureData_proto_TEXTURE_TYPE_BMP = 2,
  textureData_proto_TEXTURE_TYPE_GIF = 3,
  textureData_proto_TEXTURE_TYPE_TGA = 4,
  textureData_proto_TEXTURE_TYPE_textureData_proto_TEXTURE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_TYPE_textureData_proto_TEXTURE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_TYPE_internal_data_[];
inline constexpr textureData_proto_TEXTURE_TYPE textureData_proto_TEXTURE_TYPE_TEXTURE_TYPE_MIN =
    static_cast<textureData_proto_TEXTURE_TYPE>(0);
inline constexpr textureData_proto_TEXTURE_TYPE textureData_proto_TEXTURE_TYPE_TEXTURE_TYPE_MAX =
    static_cast<textureData_proto_TEXTURE_TYPE>(4);
inline bool textureData_proto_TEXTURE_TYPE_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int textureData_proto_TEXTURE_TYPE_TEXTURE_TYPE_ARRAYSIZE = 4 + 1;
const ::std::string& textureData_proto_TEXTURE_TYPE_Name(textureData_proto_TEXTURE_TYPE value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_TYPE_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_TYPE>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_TYPE_Name().");
  return textureData_proto_TEXTURE_TYPE_Name(static_cast<textureData_proto_TEXTURE_TYPE>(value));
}
bool textureData_proto_TEXTURE_TYPE_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_TYPE* PROTOBUF_NONNULL value);
enum textureData_proto_TEXTURE_MAG_FILTER : int {
  textureData_proto_TEXTURE_MAG_FILTER_MAG_NEAREST = 0,
  textureData_proto_TEXTURE_MAG_FILTER_MAG_LINEAR = 1,
  textureData_proto_TEXTURE_MAG_FILTER_textureData_proto_TEXTURE_MAG_FILTER_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_MAG_FILTER_textureData_proto_TEXTURE_MAG_FILTER_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_MAG_FILTER_internal_data_[];
inline constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto_TEXTURE_MAG_FILTER_TEXTURE_MAG_FILTER_MIN =
    static_cast<textureData_proto_TEXTURE_MAG_FILTER>(0);
inline constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto_TEXTURE_MAG_FILTER_TEXTURE_MAG_FILTER_MAX =
    static_cast<textureData_proto_TEXTURE_MAG_FILTER>(1);
inline bool textureData_proto_TEXTURE_MAG_FILTER_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int textureData_proto_TEXTURE_MAG_FILTER_TEXTURE_MAG_FILTER_ARRAYSIZE = 1 + 1;
const ::std::string& textureData_proto_TEXTURE_MAG_FILTER_Name(textureData_proto_TEXTURE_MAG_FILTER value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_MAG_FILTER_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_MAG_FILTER>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_MAG_FILTER_Name().");
  return textureData_proto_TEXTURE_MAG_FILTER_Name(static_cast<textureData_proto_TEXTURE_MAG_FILTER>(value));
}
bool textureData_proto_TEXTURE_MAG_FILTER_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_MAG_FILTER* PROTOBUF_NONNULL value);
enum textureData_proto_TEXTURE_MIN_FILTER : int {
  textureData_proto_TEXTURE_MIN_FILTER_MIN_NEAREST = 0,
  textureData_proto_TEXTURE_MIN_FILTER_MIN_LINEAR = 1,
  textureData_proto_TEXTURE_MIN_FILTER_MIN_NEAREST_MIPMAP_NEAREST = 2,
  textureData_proto_TEXTURE_MIN_FILTER_MIN_LINEAR_MIPMAP_NEAREST = 3,
  textureData_proto_TEXTURE_MIN_FILTER_MIN_NEAREST_MIPMAP_LINEAR = 4,
  textureData_proto_TEXTURE_MIN_FILTER_MIN_LINEAR_MIPMAP_LINEAR = 5,
  textureData_proto_TEXTURE_MIN_FILTER_textureData_proto_TEXTURE_MIN_FILTER_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_MIN_FILTER_textureData_proto_TEXTURE_MIN_FILTER_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_MIN_FILTER_internal_data_[];
inline constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto_TEXTURE_MIN_FILTER_TEXTURE_MIN_FILTER_MIN =
    static_cast<textureData_proto_TEXTURE_MIN_FILTER>(0);
inline constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto_TEXTURE_MIN_FILTER_TEXTURE_MIN_FILTER_MAX =
    static_cast<textureData_proto_TEXTURE_MIN_FILTER>(5);
inline bool textureData_proto_TEXTURE_MIN_FILTER_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int textureData_proto_TEXTURE_MIN_FILTER_TEXTURE_MIN_FILTER_ARRAYSIZE = 5 + 1;
const ::std::string& textureData_proto_TEXTURE_MIN_FILTER_Name(textureData_proto_TEXTURE_MIN_FILTER value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_MIN_FILTER_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_MIN_FILTER>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_MIN_FILTER_Name().");
  return textureData_proto_TEXTURE_MIN_FILTER_Name(static_cast<textureData_proto_TEXTURE_MIN_FILTER>(value));
}
bool textureData_proto_TEXTURE_MIN_FILTER_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_MIN_FILTER* PROTOBUF_NONNULL value);
enum textureData_proto_TEXTURE_WRAP : int {
  textureData_proto_TEXTURE_WRAP_WRAP_CLAMP_TO_EDGE = 0,
  textureData_proto_TEXTURE_WRAP_WRAP_MIRRORED_REPEAT = 1,
  textureData_proto_TEXTURE_WRAP_WRAP_REPEAT = 2,
  textureData_proto_TEXTURE_WRAP_textureData_proto_TEXTURE_WRAP_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_WRAP_textureData_proto_TEXTURE_WRAP_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_WRAP_internal_data_[];
inline constexpr textureData_proto_TEXTURE_WRAP textureData_proto_TEXTURE_WRAP_TEXTURE_WRAP_MIN =
    static_cast<textureData_proto_TEXTURE_WRAP>(0);
inline constexpr textureData_proto_TEXTURE_WRAP textureData_proto_TEXTURE_WRAP_TEXTURE_WRAP_MAX =
    static_cast<textureData_proto_TEXTURE_WRAP>(2);
inline bool textureData_proto_TEXTURE_WRAP_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int textureData_proto_TEXTURE_WRAP_TEXTURE_WRAP_ARRAYSIZE = 2 + 1;
const ::std::string& textureData_proto_TEXTURE_WRAP_Name(textureData_proto_TEXTURE_WRAP value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_WRAP_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_WRAP>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_WRAP_Name().");
  return textureData_proto_TEXTURE_WRAP_Name(static_cast<textureData_proto_TEXTURE_WRAP>(value));
}
bool textureData_proto_TEXTURE_WRAP_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_WRAP* PROTOBUF_NONNULL value);
enum textureData_proto_TEXTURE_COMPONENT : int {
  textureData_proto_TEXTURE_COMPONENT_BYTE = 0,
  textureData_proto_TEXTURE_COMPONENT_UNSIGNED_BYTE = 1,
  textureData_proto_TEXTURE_COMPONENT_SHORT = 2,
  textureData_proto_TEXTURE_COMPONENT_UNSIGNED_SHORT = 3,
  textureData_proto_TEXTURE_COMPONENT_INT = 4,
  textureData_proto_TEXTURE_COMPONENT_UNSIGNED_INT = 5,
  textureData_proto_TEXTURE_COMPONENT_FLOAT = 6,
  textureData_proto_TEXTURE_COMPONENT_DOUBLE = 7,
  textureData_proto_TEXTURE_COMPONENT_textureData_proto_TEXTURE_COMPONENT_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  textureData_proto_TEXTURE_COMPONENT_textureData_proto_TEXTURE_COMPONENT_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t textureData_proto_TEXTURE_COMPONENT_internal_data_[];
inline constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto_TEXTURE_COMPONENT_TEXTURE_COMPONENT_MIN =
    static_cast<textureData_proto_TEXTURE_COMPONENT>(0);
inline constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto_TEXTURE_COMPONENT_TEXTURE_COMPONENT_MAX =
    static_cast<textureData_proto_TEXTURE_COMPONENT>(7);
inline bool textureData_proto_TEXTURE_COMPONENT_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int textureData_proto_TEXTURE_COMPONENT_TEXTURE_COMPONENT_ARRAYSIZE = 7 + 1;
const ::std::string& textureData_proto_TEXTURE_COMPONENT_Name(textureData_proto_TEXTURE_COMPONENT value);
template <typename T>
const ::std::string& textureData_proto_TEXTURE_COMPONENT_Name(T value) {
  static_assert(::std::is_same<T, textureData_proto_TEXTURE_COMPONENT>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TEXTURE_COMPONENT_Name().");
  return textureData_proto_TEXTURE_COMPONENT_Name(static_cast<textureData_proto_TEXTURE_COMPONENT>(value));
}
bool textureData_proto_TEXTURE_COMPONENT_Parse(
    ::absl::string_view name, textureData_proto_TEXTURE_COMPONENT* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class textureData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:textureData_proto) */ {
 public:
  inline textureData_proto() : textureData_proto(nullptr) {}
  ~textureData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(textureData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(textureData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR textureData_proto(::google::protobuf::internal::ConstantInitialized);

  inline textureData_proto(const textureData_proto& from) : textureData_proto(nullptr, from) {}
  inline textureData_proto(textureData_proto&& from) noexcept
      : textureData_proto(nullptr, ::std::move(from)) {}
  inline textureData_proto& operator=(const textureData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline textureData_proto& operator=(textureData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const textureData_proto& default_instance() {
    return *reinterpret_cast<const textureData_proto*>(
        &_textureData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(textureData_proto& a, textureData_proto& b) { a.Swap(&b); }
  inline void Swap(textureData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(textureData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  textureData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<textureData_proto>(arena);
  }
  void CopyFrom(const textureData_proto& from);
  void MergeFrom(const textureData_proto& from) { textureData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(textureData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "textureData_proto"; }

 protected:
  explicit textureData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  textureData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const textureData_proto& from);
  textureData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, textureData_proto&& from) noexcept
      : textureData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using TEXTURE_EFORMAT = textureData_proto_TEXTURE_EFORMAT;
  static constexpr TEXTURE_EFORMAT EFORMAT_BGR = textureData_proto_TEXTURE_EFORMAT_EFORMAT_BGR;
  static constexpr TEXTURE_EFORMAT EFORMAT_RGB = textureData_proto_TEXTURE_EFORMAT_EFORMAT_RGB;
  static constexpr TEXTURE_EFORMAT EFORMAT_RGBA = textureData_proto_TEXTURE_EFORMAT_EFORMAT_RGBA;
  static inline bool TEXTURE_EFORMAT_IsValid(int value) {
    return textureData_proto_TEXTURE_EFORMAT_IsValid(value);
  }
  static constexpr TEXTURE_EFORMAT TEXTURE_EFORMAT_MIN = textureData_proto_TEXTURE_EFORMAT_TEXTURE_EFORMAT_MIN;
  static constexpr TEXTURE_EFORMAT TEXTURE_EFORMAT_MAX = textureData_proto_TEXTURE_EFORMAT_TEXTURE_EFORMAT_MAX;
  static constexpr int TEXTURE_EFORMAT_ARRAYSIZE = textureData_proto_TEXTURE_EFORMAT_TEXTURE_EFORMAT_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_EFORMAT_Name(T value) {
    return textureData_proto_TEXTURE_EFORMAT_Name(value);
  }
  static inline bool TEXTURE_EFORMAT_Parse(
      ::absl::string_view name, TEXTURE_EFORMAT* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_EFORMAT_Parse(name, value);
  }
  using TEXTURE_NCOMPONENT = textureData_proto_TEXTURE_NCOMPONENT;
  static constexpr TEXTURE_NCOMPONENT NCOMPONENT_BGR = textureData_proto_TEXTURE_NCOMPONENT_NCOMPONENT_BGR;
  static constexpr TEXTURE_NCOMPONENT NCOMPONENT_RGB = textureData_proto_TEXTURE_NCOMPONENT_NCOMPONENT_RGB;
  static constexpr TEXTURE_NCOMPONENT NCOMPONENT_RGBA = textureData_proto_TEXTURE_NCOMPONENT_NCOMPONENT_RGBA;
  static inline bool TEXTURE_NCOMPONENT_IsValid(int value) {
    return textureData_proto_TEXTURE_NCOMPONENT_IsValid(value);
  }
  static constexpr TEXTURE_NCOMPONENT TEXTURE_NCOMPONENT_MIN = textureData_proto_TEXTURE_NCOMPONENT_TEXTURE_NCOMPONENT_MIN;
  static constexpr TEXTURE_NCOMPONENT TEXTURE_NCOMPONENT_MAX = textureData_proto_TEXTURE_NCOMPONENT_TEXTURE_NCOMPONENT_MAX;
  static constexpr int TEXTURE_NCOMPONENT_ARRAYSIZE = textureData_proto_TEXTURE_NCOMPONENT_TEXTURE_NCOMPONENT_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_NCOMPONENT_Name(T value) {
    return textureData_proto_TEXTURE_NCOMPONENT_Name(value);
  }
  static inline bool TEXTURE_NCOMPONENT_Parse(
      ::absl::string_view name, TEXTURE_NCOMPONENT* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_NCOMPONENT_Parse(name, value);
  }
  using TEXTURE_TYPE = textureData_proto_TEXTURE_TYPE;
  static constexpr TEXTURE_TYPE JPEG = textureData_proto_TEXTURE_TYPE_JPEG;
  static constexpr TEXTURE_TYPE PNG = textureData_proto_TEXTURE_TYPE_PNG;
  static constexpr TEXTURE_TYPE BMP = textureData_proto_TEXTURE_TYPE_BMP;
  static constexpr TEXTURE_TYPE GIF = textureData_proto_TEXTURE_TYPE_GIF;
  static constexpr TEXTURE_TYPE TGA = textureData_proto_TEXTURE_TYPE_TGA;
  static inline bool TEXTURE_TYPE_IsValid(int value) {
    return textureData_proto_TEXTURE_TYPE_IsValid(value);
  }
  static constexpr TEXTURE_TYPE TEXTURE_TYPE_MIN = textureData_proto_TEXTURE_TYPE_TEXTURE_TYPE_MIN;
  static constexpr TEXTURE_TYPE TEXTURE_TYPE_MAX = textureData_proto_TEXTURE_TYPE_TEXTURE_TYPE_MAX;
  static constexpr int TEXTURE_TYPE_ARRAYSIZE = textureData_proto_TEXTURE_TYPE_TEXTURE_TYPE_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_TYPE_Name(T value) {
    return textureData_proto_TEXTURE_TYPE_Name(value);
  }
  static inline bool TEXTURE_TYPE_Parse(
      ::absl::string_view name, TEXTURE_TYPE* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_TYPE_Parse(name, value);
  }
  using TEXTURE_MAG_FILTER = textureData_proto_TEXTURE_MAG_FILTER;
  static constexpr TEXTURE_MAG_FILTER MAG_NEAREST = textureData_proto_TEXTURE_MAG_FILTER_MAG_NEAREST;
  static constexpr TEXTURE_MAG_FILTER MAG_LINEAR = textureData_proto_TEXTURE_MAG_FILTER_MAG_LINEAR;
  static inline bool TEXTURE_MAG_FILTER_IsValid(int value) {
    return textureData_proto_TEXTURE_MAG_FILTER_IsValid(value);
  }
  static constexpr TEXTURE_MAG_FILTER TEXTURE_MAG_FILTER_MIN = textureData_proto_TEXTURE_MAG_FILTER_TEXTURE_MAG_FILTER_MIN;
  static constexpr TEXTURE_MAG_FILTER TEXTURE_MAG_FILTER_MAX = textureData_proto_TEXTURE_MAG_FILTER_TEXTURE_MAG_FILTER_MAX;
  static constexpr int TEXTURE_MAG_FILTER_ARRAYSIZE = textureData_proto_TEXTURE_MAG_FILTER_TEXTURE_MAG_FILTER_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_MAG_FILTER_Name(T value) {
    return textureData_proto_TEXTURE_MAG_FILTER_Name(value);
  }
  static inline bool TEXTURE_MAG_FILTER_Parse(
      ::absl::string_view name, TEXTURE_MAG_FILTER* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_MAG_FILTER_Parse(name, value);
  }
  using TEXTURE_MIN_FILTER = textureData_proto_TEXTURE_MIN_FILTER;
  static constexpr TEXTURE_MIN_FILTER MIN_NEAREST = textureData_proto_TEXTURE_MIN_FILTER_MIN_NEAREST;
  static constexpr TEXTURE_MIN_FILTER MIN_LINEAR = textureData_proto_TEXTURE_MIN_FILTER_MIN_LINEAR;
  static constexpr TEXTURE_MIN_FILTER MIN_NEAREST_MIPMAP_NEAREST = textureData_proto_TEXTURE_MIN_FILTER_MIN_NEAREST_MIPMAP_NEAREST;
  static constexpr TEXTURE_MIN_FILTER MIN_LINEAR_MIPMAP_NEAREST = textureData_proto_TEXTURE_MIN_FILTER_MIN_LINEAR_MIPMAP_NEAREST;
  static constexpr TEXTURE_MIN_FILTER MIN_NEAREST_MIPMAP_LINEAR = textureData_proto_TEXTURE_MIN_FILTER_MIN_NEAREST_MIPMAP_LINEAR;
  static constexpr TEXTURE_MIN_FILTER MIN_LINEAR_MIPMAP_LINEAR = textureData_proto_TEXTURE_MIN_FILTER_MIN_LINEAR_MIPMAP_LINEAR;
  static inline bool TEXTURE_MIN_FILTER_IsValid(int value) {
    return textureData_proto_TEXTURE_MIN_FILTER_IsValid(value);
  }
  static constexpr TEXTURE_MIN_FILTER TEXTURE_MIN_FILTER_MIN = textureData_proto_TEXTURE_MIN_FILTER_TEXTURE_MIN_FILTER_MIN;
  static constexpr TEXTURE_MIN_FILTER TEXTURE_MIN_FILTER_MAX = textureData_proto_TEXTURE_MIN_FILTER_TEXTURE_MIN_FILTER_MAX;
  static constexpr int TEXTURE_MIN_FILTER_ARRAYSIZE = textureData_proto_TEXTURE_MIN_FILTER_TEXTURE_MIN_FILTER_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_MIN_FILTER_Name(T value) {
    return textureData_proto_TEXTURE_MIN_FILTER_Name(value);
  }
  static inline bool TEXTURE_MIN_FILTER_Parse(
      ::absl::string_view name, TEXTURE_MIN_FILTER* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_MIN_FILTER_Parse(name, value);
  }
  using TEXTURE_WRAP = textureData_proto_TEXTURE_WRAP;
  static constexpr TEXTURE_WRAP WRAP_CLAMP_TO_EDGE = textureData_proto_TEXTURE_WRAP_WRAP_CLAMP_TO_EDGE;
  static constexpr TEXTURE_WRAP WRAP_MIRRORED_REPEAT = textureData_proto_TEXTURE_WRAP_WRAP_MIRRORED_REPEAT;
  static constexpr TEXTURE_WRAP WRAP_REPEAT = textureData_proto_TEXTURE_WRAP_WRAP_REPEAT;
  static inline bool TEXTURE_WRAP_IsValid(int value) {
    return textureData_proto_TEXTURE_WRAP_IsValid(value);
  }
  static constexpr TEXTURE_WRAP TEXTURE_WRAP_MIN = textureData_proto_TEXTURE_WRAP_TEXTURE_WRAP_MIN;
  static constexpr TEXTURE_WRAP TEXTURE_WRAP_MAX = textureData_proto_TEXTURE_WRAP_TEXTURE_WRAP_MAX;
  static constexpr int TEXTURE_WRAP_ARRAYSIZE = textureData_proto_TEXTURE_WRAP_TEXTURE_WRAP_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_WRAP_Name(T value) {
    return textureData_proto_TEXTURE_WRAP_Name(value);
  }
  static inline bool TEXTURE_WRAP_Parse(
      ::absl::string_view name, TEXTURE_WRAP* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_WRAP_Parse(name, value);
  }
  using TEXTURE_COMPONENT = textureData_proto_TEXTURE_COMPONENT;
  static constexpr TEXTURE_COMPONENT BYTE = textureData_proto_TEXTURE_COMPONENT_BYTE;
  static constexpr TEXTURE_COMPONENT UNSIGNED_BYTE = textureData_proto_TEXTURE_COMPONENT_UNSIGNED_BYTE;
  static constexpr TEXTURE_COMPONENT SHORT = textureData_proto_TEXTURE_COMPONENT_SHORT;
  static constexpr TEXTURE_COMPONENT UNSIGNED_SHORT = textureData_proto_TEXTURE_COMPONENT_UNSIGNED_SHORT;
  static constexpr TEXTURE_COMPONENT INT = textureData_proto_TEXTURE_COMPONENT_INT;
  static constexpr TEXTURE_COMPONENT UNSIGNED_INT = textureData_proto_TEXTURE_COMPONENT_UNSIGNED_INT;
  static constexpr TEXTURE_COMPONENT FLOAT = textureData_proto_TEXTURE_COMPONENT_FLOAT;
  static constexpr TEXTURE_COMPONENT DOUBLE = textureData_proto_TEXTURE_COMPONENT_DOUBLE;
  static inline bool TEXTURE_COMPONENT_IsValid(int value) {
    return textureData_proto_TEXTURE_COMPONENT_IsValid(value);
  }
  static constexpr TEXTURE_COMPONENT TEXTURE_COMPONENT_MIN = textureData_proto_TEXTURE_COMPONENT_TEXTURE_COMPONENT_MIN;
  static constexpr TEXTURE_COMPONENT TEXTURE_COMPONENT_MAX = textureData_proto_TEXTURE_COMPONENT_TEXTURE_COMPONENT_MAX;
  static constexpr int TEXTURE_COMPONENT_ARRAYSIZE = textureData_proto_TEXTURE_COMPONENT_TEXTURE_COMPONENT_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& TEXTURE_COMPONENT_Name(T value) {
    return textureData_proto_TEXTURE_COMPONENT_Name(value);
  }
  static inline bool TEXTURE_COMPONENT_Parse(
      ::absl::string_view name, TEXTURE_COMPONENT* PROTOBUF_NONNULL value) {
    return textureData_proto_TEXTURE_COMPONENT_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPVersionFieldNumber = 1,
    kFileNameDataFieldNumber = 17,
    kPoDataFieldNumber = 19,
    kEnabledFieldNumber = 2,
    kTextTypeFieldNumber = 3,
    kMagFilterFieldNumber = 4,
    kMinFilterFieldNumber = 5,
    kWrapSFieldNumber = 6,
    kWrapTFieldNumber = 7,
    kEFormatFieldNumber = 8,
    kNComponentFieldNumber = 9,
    kWidthFieldNumber = 10,
    kHeightFieldNumber = 11,
    kComponentFieldNumber = 12,
    kBitsFieldNumber = 13,
    kAsIsFieldNumber = 14,
    kPixelTypeFieldNumber = 15,
    kFileNameSizeFieldNumber = 16,
    kDataSizeFieldNumber = 18,
  };
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const ::std::string& pversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pversion();
  void set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pversion();

  public:
  // optional bytes fileNameData = 17;
  bool has_filenamedata() const;
  void clear_filenamedata() ;
  const ::std::string& filenamedata() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_filenamedata(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_filenamedata();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_filenamedata();
  void set_allocated_filenamedata(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_filenamedata() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_filenamedata(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_filenamedata();

  public:
  // optional bytes poData = 19;
  bool has_podata() const;
  void clear_podata() ;
  const ::std::string& podata() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_podata(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_podata();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_podata();
  void set_allocated_podata(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_podata() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_podata(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_podata();

  public:
  // optional uint32 enabled = 2;
  bool has_enabled() const;
  void clear_enabled() ;
  ::uint32_t enabled() const;
  void set_enabled(::uint32_t value);

  private:
  ::uint32_t _internal_enabled() const;
  void _internal_set_enabled(::uint32_t value);

  public:
  // optional .textureData_proto.TEXTURE_TYPE textType = 3;
  bool has_texttype() const;
  void clear_texttype() ;
  ::textureData_proto_TEXTURE_TYPE texttype() const;
  void set_texttype(::textureData_proto_TEXTURE_TYPE value);

  private:
  ::textureData_proto_TEXTURE_TYPE _internal_texttype() const;
  void _internal_set_texttype(::textureData_proto_TEXTURE_TYPE value);

  public:
  // optional .textureData_proto.TEXTURE_MAG_FILTER magFilter = 4;
  bool has_magfilter() const;
  void clear_magfilter() ;
  ::textureData_proto_TEXTURE_MAG_FILTER magfilter() const;
  void set_magfilter(::textureData_proto_TEXTURE_MAG_FILTER value);

  private:
  ::textureData_proto_TEXTURE_MAG_FILTER _internal_magfilter() const;
  void _internal_set_magfilter(::textureData_proto_TEXTURE_MAG_FILTER value);

  public:
  // optional .textureData_proto.TEXTURE_MIN_FILTER minFilter = 5;
  bool has_minfilter() const;
  void clear_minfilter() ;
  ::textureData_proto_TEXTURE_MIN_FILTER minfilter() const;
  void set_minfilter(::textureData_proto_TEXTURE_MIN_FILTER value);

  private:
  ::textureData_proto_TEXTURE_MIN_FILTER _internal_minfilter() const;
  void _internal_set_minfilter(::textureData_proto_TEXTURE_MIN_FILTER value);

  public:
  // optional .textureData_proto.TEXTURE_WRAP wrapS = 6;
  bool has_wraps() const;
  void clear_wraps() ;
  ::textureData_proto_TEXTURE_WRAP wraps() const;
  void set_wraps(::textureData_proto_TEXTURE_WRAP value);

  private:
  ::textureData_proto_TEXTURE_WRAP _internal_wraps() const;
  void _internal_set_wraps(::textureData_proto_TEXTURE_WRAP value);

  public:
  // optional .textureData_proto.TEXTURE_WRAP wrapT = 7;
  bool has_wrapt() const;
  void clear_wrapt() ;
  ::textureData_proto_TEXTURE_WRAP wrapt() const;
  void set_wrapt(::textureData_proto_TEXTURE_WRAP value);

  private:
  ::textureData_proto_TEXTURE_WRAP _internal_wrapt() const;
  void _internal_set_wrapt(::textureData_proto_TEXTURE_WRAP value);

  public:
  // optional .textureData_proto.TEXTURE_EFORMAT eFormat = 8;
  bool has_eformat() const;
  void clear_eformat() ;
  ::textureData_proto_TEXTURE_EFORMAT eformat() const;
  void set_eformat(::textureData_proto_TEXTURE_EFORMAT value);

  private:
  ::textureData_proto_TEXTURE_EFORMAT _internal_eformat() const;
  void _internal_set_eformat(::textureData_proto_TEXTURE_EFORMAT value);

  public:
  // optional .textureData_proto.TEXTURE_NCOMPONENT nComponent = 9;
  bool has_ncomponent() const;
  void clear_ncomponent() ;
  ::textureData_proto_TEXTURE_NCOMPONENT ncomponent() const;
  void set_ncomponent(::textureData_proto_TEXTURE_NCOMPONENT value);

  private:
  ::textureData_proto_TEXTURE_NCOMPONENT _internal_ncomponent() const;
  void _internal_set_ncomponent(::textureData_proto_TEXTURE_NCOMPONENT value);

  public:
  // optional uint32 width = 10;
  bool has_width() const;
  void clear_width() ;
  ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // optional uint32 height = 11;
  bool has_height() const;
  void clear_height() ;
  ::uint32_t height() const;
  void set_height(::uint32_t value);

  private:
  ::uint32_t _internal_height() const;
  void _internal_set_height(::uint32_t value);

  public:
  // optional uint32 component = 12;
  bool has_component() const;
  void clear_component() ;
  ::uint32_t component() const;
  void set_component(::uint32_t value);

  private:
  ::uint32_t _internal_component() const;
  void _internal_set_component(::uint32_t value);

  public:
  // optional uint32 bits = 13;
  bool has_bits() const;
  void clear_bits() ;
  ::uint32_t bits() const;
  void set_bits(::uint32_t value);

  private:
  ::uint32_t _internal_bits() const;
  void _internal_set_bits(::uint32_t value);

  public:
  // optional uint32 as_is = 14;
  bool has_as_is() const;
  void clear_as_is() ;
  ::uint32_t as_is() const;
  void set_as_is(::uint32_t value);

  private:
  ::uint32_t _internal_as_is() const;
  void _internal_set_as_is(::uint32_t value);

  public:
  // optional .textureData_proto.TEXTURE_COMPONENT pixel_type = 15;
  bool has_pixel_type() const;
  void clear_pixel_type() ;
  ::textureData_proto_TEXTURE_COMPONENT pixel_type() const;
  void set_pixel_type(::textureData_proto_TEXTURE_COMPONENT value);

  private:
  ::textureData_proto_TEXTURE_COMPONENT _internal_pixel_type() const;
  void _internal_set_pixel_type(::textureData_proto_TEXTURE_COMPONENT value);

  public:
  // optional uint32 fileNameSize = 16;
  bool has_filenamesize() const;
  void clear_filenamesize() ;
  ::uint32_t filenamesize() const;
  void set_filenamesize(::uint32_t value);

  private:
  ::uint32_t _internal_filenamesize() const;
  void _internal_set_filenamesize(::uint32_t value);

  public:
  // optional uint32 dataSize = 18;
  bool has_datasize() const;
  void clear_datasize() ;
  ::uint32_t datasize() const;
  void set_datasize(::uint32_t value);

  private:
  ::uint32_t _internal_datasize() const;
  void _internal_set_datasize(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:textureData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 19,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const textureData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::google::protobuf::internal::ArenaStringPtr filenamedata_;
    ::google::protobuf::internal::ArenaStringPtr podata_;
    ::uint32_t enabled_;
    int texttype_;
    int magfilter_;
    int minfilter_;
    int wraps_;
    int wrapt_;
    int eformat_;
    int ncomponent_;
    ::uint32_t width_;
    ::uint32_t height_;
    ::uint32_t component_;
    ::uint32_t bits_;
    ::uint32_t as_is_;
    int pixel_type_;
    ::uint32_t filenamesize_;
    ::uint32_t datasize_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_textureData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<18> textureData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// textureData_proto

// optional bytes pVersion = 1;
inline bool textureData_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void textureData_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& textureData_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textureData_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void textureData_proto::set_pversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textureData_proto.pVersion)
}
inline ::std::string* PROTOBUF_NONNULL textureData_proto::mutable_pversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:textureData_proto.pVersion)
  return _s;
}
inline const ::std::string& textureData_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void textureData_proto::_internal_set_pversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL textureData_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE textureData_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textureData_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pversion_.Set("", GetArena());
  }
  return released;
}
inline void textureData_proto::set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pversion_.IsDefault()) {
    _impl_.pversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textureData_proto.pVersion)
}

// optional uint32 enabled = 2;
inline bool textureData_proto::has_enabled() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void textureData_proto::clear_enabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enabled_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline ::uint32_t textureData_proto::enabled() const {
  // @@protoc_insertion_point(field_get:textureData_proto.enabled)
  return _internal_enabled();
}
inline void textureData_proto::set_enabled(::uint32_t value) {
  _internal_set_enabled(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:textureData_proto.enabled)
}
inline ::uint32_t textureData_proto::_internal_enabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enabled_;
}
inline void textureData_proto::_internal_set_enabled(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enabled_ = value;
}

// optional .textureData_proto.TEXTURE_TYPE textType = 3;
inline bool textureData_proto::has_texttype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010U) != 0;
  return value;
}
inline void textureData_proto::clear_texttype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texttype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline ::textureData_proto_TEXTURE_TYPE textureData_proto::texttype() const {
  // @@protoc_insertion_point(field_get:textureData_proto.textType)
  return _internal_texttype();
}
inline void textureData_proto::set_texttype(::textureData_proto_TEXTURE_TYPE value) {
  _internal_set_texttype(value);
  _impl_._has_bits_[0] |= 0x00000010U;
  // @@protoc_insertion_point(field_set:textureData_proto.textType)
}
inline ::textureData_proto_TEXTURE_TYPE textureData_proto::_internal_texttype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_TYPE>(_impl_.texttype_);
}
inline void textureData_proto::_internal_set_texttype(::textureData_proto_TEXTURE_TYPE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texttype_ = value;
}

// optional .textureData_proto.TEXTURE_MAG_FILTER magFilter = 4;
inline bool textureData_proto::has_magfilter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020U) != 0;
  return value;
}
inline void textureData_proto::clear_magfilter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magfilter_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline ::textureData_proto_TEXTURE_MAG_FILTER textureData_proto::magfilter() const {
  // @@protoc_insertion_point(field_get:textureData_proto.magFilter)
  return _internal_magfilter();
}
inline void textureData_proto::set_magfilter(::textureData_proto_TEXTURE_MAG_FILTER value) {
  _internal_set_magfilter(value);
  _impl_._has_bits_[0] |= 0x00000020U;
  // @@protoc_insertion_point(field_set:textureData_proto.magFilter)
}
inline ::textureData_proto_TEXTURE_MAG_FILTER textureData_proto::_internal_magfilter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_MAG_FILTER>(_impl_.magfilter_);
}
inline void textureData_proto::_internal_set_magfilter(::textureData_proto_TEXTURE_MAG_FILTER value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magfilter_ = value;
}

// optional .textureData_proto.TEXTURE_MIN_FILTER minFilter = 5;
inline bool textureData_proto::has_minfilter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040U) != 0;
  return value;
}
inline void textureData_proto::clear_minfilter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.minfilter_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline ::textureData_proto_TEXTURE_MIN_FILTER textureData_proto::minfilter() const {
  // @@protoc_insertion_point(field_get:textureData_proto.minFilter)
  return _internal_minfilter();
}
inline void textureData_proto::set_minfilter(::textureData_proto_TEXTURE_MIN_FILTER value) {
  _internal_set_minfilter(value);
  _impl_._has_bits_[0] |= 0x00000040U;
  // @@protoc_insertion_point(field_set:textureData_proto.minFilter)
}
inline ::textureData_proto_TEXTURE_MIN_FILTER textureData_proto::_internal_minfilter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_MIN_FILTER>(_impl_.minfilter_);
}
inline void textureData_proto::_internal_set_minfilter(::textureData_proto_TEXTURE_MIN_FILTER value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.minfilter_ = value;
}

// optional .textureData_proto.TEXTURE_WRAP wrapS = 6;
inline bool textureData_proto::has_wraps() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080U) != 0;
  return value;
}
inline void textureData_proto::clear_wraps() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wraps_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080U;
}
inline ::textureData_proto_TEXTURE_WRAP textureData_proto::wraps() const {
  // @@protoc_insertion_point(field_get:textureData_proto.wrapS)
  return _internal_wraps();
}
inline void textureData_proto::set_wraps(::textureData_proto_TEXTURE_WRAP value) {
  _internal_set_wraps(value);
  _impl_._has_bits_[0] |= 0x00000080U;
  // @@protoc_insertion_point(field_set:textureData_proto.wrapS)
}
inline ::textureData_proto_TEXTURE_WRAP textureData_proto::_internal_wraps() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_WRAP>(_impl_.wraps_);
}
inline void textureData_proto::_internal_set_wraps(::textureData_proto_TEXTURE_WRAP value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wraps_ = value;
}

// optional .textureData_proto.TEXTURE_WRAP wrapT = 7;
inline bool textureData_proto::has_wrapt() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100U) != 0;
  return value;
}
inline void textureData_proto::clear_wrapt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wrapt_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100U;
}
inline ::textureData_proto_TEXTURE_WRAP textureData_proto::wrapt() const {
  // @@protoc_insertion_point(field_get:textureData_proto.wrapT)
  return _internal_wrapt();
}
inline void textureData_proto::set_wrapt(::textureData_proto_TEXTURE_WRAP value) {
  _internal_set_wrapt(value);
  _impl_._has_bits_[0] |= 0x00000100U;
  // @@protoc_insertion_point(field_set:textureData_proto.wrapT)
}
inline ::textureData_proto_TEXTURE_WRAP textureData_proto::_internal_wrapt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_WRAP>(_impl_.wrapt_);
}
inline void textureData_proto::_internal_set_wrapt(::textureData_proto_TEXTURE_WRAP value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wrapt_ = value;
}

// optional .textureData_proto.TEXTURE_EFORMAT eFormat = 8;
inline bool textureData_proto::has_eformat() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200U) != 0;
  return value;
}
inline void textureData_proto::clear_eformat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eformat_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200U;
}
inline ::textureData_proto_TEXTURE_EFORMAT textureData_proto::eformat() const {
  // @@protoc_insertion_point(field_get:textureData_proto.eFormat)
  return _internal_eformat();
}
inline void textureData_proto::set_eformat(::textureData_proto_TEXTURE_EFORMAT value) {
  _internal_set_eformat(value);
  _impl_._has_bits_[0] |= 0x00000200U;
  // @@protoc_insertion_point(field_set:textureData_proto.eFormat)
}
inline ::textureData_proto_TEXTURE_EFORMAT textureData_proto::_internal_eformat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_EFORMAT>(_impl_.eformat_);
}
inline void textureData_proto::_internal_set_eformat(::textureData_proto_TEXTURE_EFORMAT value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eformat_ = value;
}

// optional .textureData_proto.TEXTURE_NCOMPONENT nComponent = 9;
inline bool textureData_proto::has_ncomponent() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400U) != 0;
  return value;
}
inline void textureData_proto::clear_ncomponent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ncomponent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400U;
}
inline ::textureData_proto_TEXTURE_NCOMPONENT textureData_proto::ncomponent() const {
  // @@protoc_insertion_point(field_get:textureData_proto.nComponent)
  return _internal_ncomponent();
}
inline void textureData_proto::set_ncomponent(::textureData_proto_TEXTURE_NCOMPONENT value) {
  _internal_set_ncomponent(value);
  _impl_._has_bits_[0] |= 0x00000400U;
  // @@protoc_insertion_point(field_set:textureData_proto.nComponent)
}
inline ::textureData_proto_TEXTURE_NCOMPONENT textureData_proto::_internal_ncomponent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_NCOMPONENT>(_impl_.ncomponent_);
}
inline void textureData_proto::_internal_set_ncomponent(::textureData_proto_TEXTURE_NCOMPONENT value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ncomponent_ = value;
}

// optional uint32 width = 10;
inline bool textureData_proto::has_width() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800U) != 0;
  return value;
}
inline void textureData_proto::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000800U;
}
inline ::uint32_t textureData_proto::width() const {
  // @@protoc_insertion_point(field_get:textureData_proto.width)
  return _internal_width();
}
inline void textureData_proto::set_width(::uint32_t value) {
  _internal_set_width(value);
  _impl_._has_bits_[0] |= 0x00000800U;
  // @@protoc_insertion_point(field_set:textureData_proto.width)
}
inline ::uint32_t textureData_proto::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void textureData_proto::_internal_set_width(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// optional uint32 height = 11;
inline bool textureData_proto::has_height() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000U) != 0;
  return value;
}
inline void textureData_proto::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0u;
  _impl_._has_bits_[0] &= ~0x00001000U;
}
inline ::uint32_t textureData_proto::height() const {
  // @@protoc_insertion_point(field_get:textureData_proto.height)
  return _internal_height();
}
inline void textureData_proto::set_height(::uint32_t value) {
  _internal_set_height(value);
  _impl_._has_bits_[0] |= 0x00001000U;
  // @@protoc_insertion_point(field_set:textureData_proto.height)
}
inline ::uint32_t textureData_proto::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void textureData_proto::_internal_set_height(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// optional uint32 component = 12;
inline bool textureData_proto::has_component() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000U) != 0;
  return value;
}
inline void textureData_proto::clear_component() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.component_ = 0u;
  _impl_._has_bits_[0] &= ~0x00002000U;
}
inline ::uint32_t textureData_proto::component() const {
  // @@protoc_insertion_point(field_get:textureData_proto.component)
  return _internal_component();
}
inline void textureData_proto::set_component(::uint32_t value) {
  _internal_set_component(value);
  _impl_._has_bits_[0] |= 0x00002000U;
  // @@protoc_insertion_point(field_set:textureData_proto.component)
}
inline ::uint32_t textureData_proto::_internal_component() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.component_;
}
inline void textureData_proto::_internal_set_component(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.component_ = value;
}

// optional uint32 bits = 13;
inline bool textureData_proto::has_bits() const {
  bool value = (_impl_._has_bits_[0] & 0x00004000U) != 0;
  return value;
}
inline void textureData_proto::clear_bits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bits_ = 0u;
  _impl_._has_bits_[0] &= ~0x00004000U;
}
inline ::uint32_t textureData_proto::bits() const {
  // @@protoc_insertion_point(field_get:textureData_proto.bits)
  return _internal_bits();
}
inline void textureData_proto::set_bits(::uint32_t value) {
  _internal_set_bits(value);
  _impl_._has_bits_[0] |= 0x00004000U;
  // @@protoc_insertion_point(field_set:textureData_proto.bits)
}
inline ::uint32_t textureData_proto::_internal_bits() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bits_;
}
inline void textureData_proto::_internal_set_bits(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bits_ = value;
}

// optional uint32 as_is = 14;
inline bool textureData_proto::has_as_is() const {
  bool value = (_impl_._has_bits_[0] & 0x00008000U) != 0;
  return value;
}
inline void textureData_proto::clear_as_is() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.as_is_ = 0u;
  _impl_._has_bits_[0] &= ~0x00008000U;
}
inline ::uint32_t textureData_proto::as_is() const {
  // @@protoc_insertion_point(field_get:textureData_proto.as_is)
  return _internal_as_is();
}
inline void textureData_proto::set_as_is(::uint32_t value) {
  _internal_set_as_is(value);
  _impl_._has_bits_[0] |= 0x00008000U;
  // @@protoc_insertion_point(field_set:textureData_proto.as_is)
}
inline ::uint32_t textureData_proto::_internal_as_is() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.as_is_;
}
inline void textureData_proto::_internal_set_as_is(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.as_is_ = value;
}

// optional .textureData_proto.TEXTURE_COMPONENT pixel_type = 15;
inline bool textureData_proto::has_pixel_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00010000U) != 0;
  return value;
}
inline void textureData_proto::clear_pixel_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pixel_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000U;
}
inline ::textureData_proto_TEXTURE_COMPONENT textureData_proto::pixel_type() const {
  // @@protoc_insertion_point(field_get:textureData_proto.pixel_type)
  return _internal_pixel_type();
}
inline void textureData_proto::set_pixel_type(::textureData_proto_TEXTURE_COMPONENT value) {
  _internal_set_pixel_type(value);
  _impl_._has_bits_[0] |= 0x00010000U;
  // @@protoc_insertion_point(field_set:textureData_proto.pixel_type)
}
inline ::textureData_proto_TEXTURE_COMPONENT textureData_proto::_internal_pixel_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::textureData_proto_TEXTURE_COMPONENT>(_impl_.pixel_type_);
}
inline void textureData_proto::_internal_set_pixel_type(::textureData_proto_TEXTURE_COMPONENT value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pixel_type_ = value;
}

// optional uint32 fileNameSize = 16;
inline bool textureData_proto::has_filenamesize() const {
  bool value = (_impl_._has_bits_[0] & 0x00020000U) != 0;
  return value;
}
inline void textureData_proto::clear_filenamesize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filenamesize_ = 0u;
  _impl_._has_bits_[0] &= ~0x00020000U;
}
inline ::uint32_t textureData_proto::filenamesize() const {
  // @@protoc_insertion_point(field_get:textureData_proto.fileNameSize)
  return _internal_filenamesize();
}
inline void textureData_proto::set_filenamesize(::uint32_t value) {
  _internal_set_filenamesize(value);
  _impl_._has_bits_[0] |= 0x00020000U;
  // @@protoc_insertion_point(field_set:textureData_proto.fileNameSize)
}
inline ::uint32_t textureData_proto::_internal_filenamesize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filenamesize_;
}
inline void textureData_proto::_internal_set_filenamesize(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filenamesize_ = value;
}

// optional bytes fileNameData = 17;
inline bool textureData_proto::has_filenamedata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void textureData_proto::clear_filenamedata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filenamedata_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& textureData_proto::filenamedata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textureData_proto.fileNameData)
  return _internal_filenamedata();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void textureData_proto::set_filenamedata(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.filenamedata_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textureData_proto.fileNameData)
}
inline ::std::string* PROTOBUF_NONNULL textureData_proto::mutable_filenamedata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_filenamedata();
  // @@protoc_insertion_point(field_mutable:textureData_proto.fileNameData)
  return _s;
}
inline const ::std::string& textureData_proto::_internal_filenamedata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filenamedata_.Get();
}
inline void textureData_proto::_internal_set_filenamedata(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.filenamedata_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL textureData_proto::_internal_mutable_filenamedata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.filenamedata_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE textureData_proto::release_filenamedata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textureData_proto.fileNameData)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.filenamedata_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filenamedata_.Set("", GetArena());
  }
  return released;
}
inline void textureData_proto::set_allocated_filenamedata(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.filenamedata_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filenamedata_.IsDefault()) {
    _impl_.filenamedata_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textureData_proto.fileNameData)
}

// optional uint32 dataSize = 18;
inline bool textureData_proto::has_datasize() const {
  bool value = (_impl_._has_bits_[0] & 0x00040000U) != 0;
  return value;
}
inline void textureData_proto::clear_datasize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datasize_ = 0u;
  _impl_._has_bits_[0] &= ~0x00040000U;
}
inline ::uint32_t textureData_proto::datasize() const {
  // @@protoc_insertion_point(field_get:textureData_proto.dataSize)
  return _internal_datasize();
}
inline void textureData_proto::set_datasize(::uint32_t value) {
  _internal_set_datasize(value);
  _impl_._has_bits_[0] |= 0x00040000U;
  // @@protoc_insertion_point(field_set:textureData_proto.dataSize)
}
inline ::uint32_t textureData_proto::_internal_datasize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.datasize_;
}
inline void textureData_proto::_internal_set_datasize(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datasize_ = value;
}

// optional bytes poData = 19;
inline bool textureData_proto::has_podata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void textureData_proto::clear_podata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.podata_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::std::string& textureData_proto::podata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:textureData_proto.poData)
  return _internal_podata();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void textureData_proto::set_podata(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.podata_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:textureData_proto.poData)
}
inline ::std::string* PROTOBUF_NONNULL textureData_proto::mutable_podata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_podata();
  // @@protoc_insertion_point(field_mutable:textureData_proto.poData)
  return _s;
}
inline const ::std::string& textureData_proto::_internal_podata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.podata_.Get();
}
inline void textureData_proto::_internal_set_podata(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.podata_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL textureData_proto::_internal_mutable_podata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  return _impl_.podata_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE textureData_proto::release_podata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:textureData_proto.poData)
  if ((_impl_._has_bits_[0] & 0x00000004U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004U;
  auto* released = _impl_.podata_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.podata_.Set("", GetArena());
  }
  return released;
}
inline void textureData_proto::set_allocated_podata(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  _impl_.podata_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.podata_.IsDefault()) {
    _impl_.podata_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:textureData_proto.poData)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::textureData_proto_TEXTURE_EFORMAT> : std::true_type {};
template <>
struct is_proto_enum<::textureData_proto_TEXTURE_NCOMPONENT> : std::true_type {};
template <>
struct is_proto_enum<::textureData_proto_TEXTURE_TYPE> : std::true_type {};
template <>
struct is_proto_enum<::textureData_proto_TEXTURE_MAG_FILTER> : std::true_type {};
template <>
struct is_proto_enum<::textureData_proto_TEXTURE_MIN_FILTER> : std::true_type {};
template <>
struct is_proto_enum<::textureData_proto_TEXTURE_WRAP> : std::true_type {};
template <>
struct is_proto_enum<::textureData_proto_TEXTURE_COMPONENT> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // textureData_2eproto_2epb_2eh
