// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vboData.proto
// Protobuf C++ Version: 6.32.0-dev

#include "vboData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr vboData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        podata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        enabled_{0u},
        targettype_{static_cast< ::vboData_proto_VBO_TARGET >(0)},
        componenttype_{static_cast< ::vboData_proto_VBO_COMPONENT >(0)},
        vbotype_{static_cast< ::vboData_proto_VBO_TYPE >(0)},
        stride_{0u},
        count_{0u},
        datasize_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR vboData_proto::vboData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(vboData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct vboData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR vboData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~vboData_protoDefaultTypeInternal() {}
  union {
    vboData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 vboData_protoDefaultTypeInternal _vboData_proto_default_instance_;
PROTOBUF_CONSTINIT const uint32_t vboData_proto_VBO_TARGET_internal_data_[] = {
    131072u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    vboData_proto_VBO_TARGET_strings[2] = {};

static const char vboData_proto_VBO_TARGET_names[] = {
    "ARRAY_BUFFER"
    "ELEMENT_ARRAY_BUFFER"
};

static const ::google::protobuf::internal::EnumEntry vboData_proto_VBO_TARGET_entries[] = {
    {{&vboData_proto_VBO_TARGET_names[0], 12}, 0},
    {{&vboData_proto_VBO_TARGET_names[12], 20}, 1},
};

static const int vboData_proto_VBO_TARGET_entries_by_number[] = {
    0,  // 0 -> ARRAY_BUFFER
    1,  // 1 -> ELEMENT_ARRAY_BUFFER
};

const ::std::string& vboData_proto_VBO_TARGET_Name(vboData_proto_VBO_TARGET value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      vboData_proto_VBO_TARGET_entries, vboData_proto_VBO_TARGET_entries_by_number, 2,
      vboData_proto_VBO_TARGET_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(vboData_proto_VBO_TARGET_entries,
                                  vboData_proto_VBO_TARGET_entries_by_number,
                                  2, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : vboData_proto_VBO_TARGET_strings[idx].get();
}

bool vboData_proto_VBO_TARGET_Parse(::absl::string_view name, vboData_proto_VBO_TARGET* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      vboData_proto_VBO_TARGET_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<vboData_proto_VBO_TARGET>(int_value);
  }
  return success;
}
PROTOBUF_CONSTINIT const uint32_t vboData_proto_VBO_COMPONENT_internal_data_[] = {
    524288u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    vboData_proto_VBO_COMPONENT_strings[8] = {};

static const char vboData_proto_VBO_COMPONENT_names[] = {
    "BYTE"
    "DOUBLE"
    "FLOAT"
    "INT"
    "SHORT"
    "UNSIGNED_BYTE"
    "UNSIGNED_INT"
    "UNSIGNED_SHORT"
};

static const ::google::protobuf::internal::EnumEntry vboData_proto_VBO_COMPONENT_entries[] = {
    {{&vboData_proto_VBO_COMPONENT_names[0], 4}, 0},
    {{&vboData_proto_VBO_COMPONENT_names[4], 6}, 7},
    {{&vboData_proto_VBO_COMPONENT_names[10], 5}, 6},
    {{&vboData_proto_VBO_COMPONENT_names[15], 3}, 4},
    {{&vboData_proto_VBO_COMPONENT_names[18], 5}, 2},
    {{&vboData_proto_VBO_COMPONENT_names[23], 13}, 1},
    {{&vboData_proto_VBO_COMPONENT_names[36], 12}, 5},
    {{&vboData_proto_VBO_COMPONENT_names[48], 14}, 3},
};

static const int vboData_proto_VBO_COMPONENT_entries_by_number[] = {
    0,  // 0 -> BYTE
    5,  // 1 -> UNSIGNED_BYTE
    4,  // 2 -> SHORT
    7,  // 3 -> UNSIGNED_SHORT
    3,  // 4 -> INT
    6,  // 5 -> UNSIGNED_INT
    2,  // 6 -> FLOAT
    1,  // 7 -> DOUBLE
};

const ::std::string& vboData_proto_VBO_COMPONENT_Name(vboData_proto_VBO_COMPONENT value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      vboData_proto_VBO_COMPONENT_entries, vboData_proto_VBO_COMPONENT_entries_by_number, 8,
      vboData_proto_VBO_COMPONENT_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(vboData_proto_VBO_COMPONENT_entries,
                                  vboData_proto_VBO_COMPONENT_entries_by_number,
                                  8, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : vboData_proto_VBO_COMPONENT_strings[idx].get();
}

bool vboData_proto_VBO_COMPONENT_Parse(::absl::string_view name, vboData_proto_VBO_COMPONENT* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      vboData_proto_VBO_COMPONENT_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<vboData_proto_VBO_COMPONENT>(int_value);
  }
  return success;
}
PROTOBUF_CONSTINIT const uint32_t vboData_proto_VBO_TYPE_internal_data_[] = {
    589824u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    vboData_proto_VBO_TYPE_strings[9] = {};

static const char vboData_proto_VBO_TYPE_names[] = {
    "MAT2"
    "MAT3"
    "MAT4"
    "MATRIX"
    "SCALAR"
    "VEC2"
    "VEC3"
    "VEC4"
    "VECTOR"
};

static const ::google::protobuf::internal::EnumEntry vboData_proto_VBO_TYPE_entries[] = {
    {{&vboData_proto_VBO_TYPE_names[0], 4}, 3},
    {{&vboData_proto_VBO_TYPE_names[4], 4}, 4},
    {{&vboData_proto_VBO_TYPE_names[8], 4}, 5},
    {{&vboData_proto_VBO_TYPE_names[12], 6}, 8},
    {{&vboData_proto_VBO_TYPE_names[18], 6}, 6},
    {{&vboData_proto_VBO_TYPE_names[24], 4}, 0},
    {{&vboData_proto_VBO_TYPE_names[28], 4}, 1},
    {{&vboData_proto_VBO_TYPE_names[32], 4}, 2},
    {{&vboData_proto_VBO_TYPE_names[36], 6}, 7},
};

static const int vboData_proto_VBO_TYPE_entries_by_number[] = {
    5,  // 0 -> VEC2
    6,  // 1 -> VEC3
    7,  // 2 -> VEC4
    0,  // 3 -> MAT2
    1,  // 4 -> MAT3
    2,  // 5 -> MAT4
    4,  // 6 -> SCALAR
    8,  // 7 -> VECTOR
    3,  // 8 -> MATRIX
};

const ::std::string& vboData_proto_VBO_TYPE_Name(vboData_proto_VBO_TYPE value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      vboData_proto_VBO_TYPE_entries, vboData_proto_VBO_TYPE_entries_by_number, 9,
      vboData_proto_VBO_TYPE_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(vboData_proto_VBO_TYPE_entries,
                                  vboData_proto_VBO_TYPE_entries_by_number,
                                  9, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : vboData_proto_VBO_TYPE_strings[idx].get();
}

bool vboData_proto_VBO_TYPE_Parse(::absl::string_view name, vboData_proto_VBO_TYPE* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      vboData_proto_VBO_TYPE_entries, 9, name, &int_value);
  if (success) {
    *value = static_cast<vboData_proto_VBO_TYPE>(int_value);
  }
  return success;
}
// ===================================================================

class vboData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<vboData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_._has_bits_);
};

vboData_proto::vboData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, vboData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vboData_proto)
}
PROTOBUF_NDEBUG_INLINE vboData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vboData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        podata_(arena, from.podata_) {}

vboData_proto::vboData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const vboData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, vboData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  vboData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, enabled_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, enabled_),
           offsetof(Impl_, datasize_) -
               offsetof(Impl_, enabled_) +
               sizeof(Impl_::datasize_));

  // @@protoc_insertion_point(copy_constructor:vboData_proto)
}
PROTOBUF_NDEBUG_INLINE vboData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        podata_(arena) {}

inline void vboData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, enabled_),
           0,
           offsetof(Impl_, datasize_) -
               offsetof(Impl_, enabled_) +
               sizeof(Impl_::datasize_));
}
vboData_proto::~vboData_proto() {
  // @@protoc_insertion_point(destructor:vboData_proto)
  SharedDtor(*this);
}
inline void vboData_proto::SharedDtor(MessageLite& self) {
  vboData_proto& this_ = static_cast<vboData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.podata_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL vboData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) vboData_proto(arena);
}
constexpr auto vboData_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(vboData_proto),
                                            alignof(vboData_proto));
}
constexpr auto vboData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<14>{
      {
          &_vboData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &vboData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<vboData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &vboData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<vboData_proto>(), &vboData_proto::ByteSizeLong,
              &vboData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_._cached_size_),
          true,
      },
      "vboData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<14> vboData_proto_class_data_ =
    vboData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
vboData_proto::GetClassData() const {
  return vboData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 0, 2>
vboData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    vboData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vboData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes poData = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 0, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.podata_)}},
    // optional uint32 enabled = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.enabled_)}},
    // optional .vboData_proto.VBO_TARGET targetType = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.targettype_)}},
    // optional .vboData_proto.VBO_COMPONENT componentType = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 3, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.componenttype_)}},
    // optional .vboData_proto.VBO_TYPE vboType = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 4, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.vbotype_)}},
    // optional uint32 stride = 5;
    {::_pbi::TcParser::FastV32S1,
     {40, 5, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.stride_)}},
    // optional uint32 count = 6;
    {::_pbi::TcParser::FastV32S1,
     {48, 6, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.count_)}},
    // optional uint32 dataSize = 7;
    {::_pbi::TcParser::FastV32S1,
     {56, 7, 0, PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.datasize_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 enabled = 1;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.enabled_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .vboData_proto.VBO_TARGET targetType = 2;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.targettype_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional .vboData_proto.VBO_COMPONENT componentType = 3;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.componenttype_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional .vboData_proto.VBO_TYPE vboType = 4;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.vbotype_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional uint32 stride = 5;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.stride_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 count = 6;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.count_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 dataSize = 7;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.datasize_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional bytes poData = 8;
    {PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.podata_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void vboData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:vboData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.podata_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x000000feU) != 0) {
    ::memset(&_impl_.enabled_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.datasize_) -
        reinterpret_cast<char*>(&_impl_.enabled_)) + sizeof(_impl_.datasize_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL vboData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const vboData_proto& this_ = static_cast<const vboData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL vboData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const vboData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vboData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 enabled = 1;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_enabled(), target);
  }

  // optional .vboData_proto.VBO_TARGET targetType = 2;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_targettype(), target);
  }

  // optional .vboData_proto.VBO_COMPONENT componentType = 3;
  if ((cached_has_bits & 0x00000008U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this_._internal_componenttype(), target);
  }

  // optional .vboData_proto.VBO_TYPE vboType = 4;
  if ((cached_has_bits & 0x00000010U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        4, this_._internal_vbotype(), target);
  }

  // optional uint32 stride = 5;
  if ((cached_has_bits & 0x00000020U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_stride(), target);
  }

  // optional uint32 count = 6;
  if ((cached_has_bits & 0x00000040U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_count(), target);
  }

  // optional uint32 dataSize = 7;
  if ((cached_has_bits & 0x00000080U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this_._internal_datasize(), target);
  }

  // optional bytes poData = 8;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_podata();
    target = stream->WriteBytesMaybeAliased(8, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vboData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t vboData_proto::ByteSizeLong(const MessageLite& base) {
  const vboData_proto& this_ = static_cast<const vboData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t vboData_proto::ByteSizeLong() const {
  const vboData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vboData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    // optional bytes poData = 8;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_podata());
    }
    // optional uint32 enabled = 1;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_enabled());
    }
    // optional .vboData_proto.VBO_TARGET targetType = 2;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_targettype());
    }
    // optional .vboData_proto.VBO_COMPONENT componentType = 3;
    if ((cached_has_bits & 0x00000008U) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_componenttype());
    }
    // optional .vboData_proto.VBO_TYPE vboType = 4;
    if ((cached_has_bits & 0x00000010U) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_vbotype());
    }
    // optional uint32 stride = 5;
    if ((cached_has_bits & 0x00000020U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_stride());
    }
    // optional uint32 count = 6;
    if ((cached_has_bits & 0x00000040U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_count());
    }
    // optional uint32 dataSize = 7;
    if ((cached_has_bits & 0x00000080U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_datasize());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void vboData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<vboData_proto*>(&to_msg);
  auto& from = static_cast<const vboData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vboData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_podata(from._internal_podata());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.enabled_ = from._impl_.enabled_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.targettype_ = from._impl_.targettype_;
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _this->_impl_.componenttype_ = from._impl_.componenttype_;
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      _this->_impl_.vbotype_ = from._impl_.vbotype_;
    }
    if ((cached_has_bits & 0x00000020U) != 0) {
      _this->_impl_.stride_ = from._impl_.stride_;
    }
    if ((cached_has_bits & 0x00000040U) != 0) {
      _this->_impl_.count_ = from._impl_.count_;
    }
    if ((cached_has_bits & 0x00000080U) != 0) {
      _this->_impl_.datasize_ = from._impl_.datasize_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void vboData_proto::CopyFrom(const vboData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vboData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void vboData_proto::InternalSwap(vboData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.podata_, &other->_impl_.podata_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.datasize_)
      + sizeof(vboData_proto::_impl_.datasize_)
      - PROTOBUF_FIELD_OFFSET(vboData_proto, _impl_.enabled_)>(
          reinterpret_cast<char*>(&_impl_.enabled_),
          reinterpret_cast<char*>(&other->_impl_.enabled_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
