// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vboData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef vboData_2eproto_2epb_2eh
#define vboData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vboData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_vboData_2eproto {
  static const ::uint32_t offsets[];
};
enum vboData_proto_VBO_COMPONENT : int;
extern const uint32_t vboData_proto_VBO_COMPONENT_internal_data_[];
enum vboData_proto_VBO_TARGET : int;
extern const uint32_t vboData_proto_VBO_TARGET_internal_data_[];
enum vboData_proto_VBO_TYPE : int;
extern const uint32_t vboData_proto_VBO_TYPE_internal_data_[];
class vboData_proto;
struct vboData_protoDefaultTypeInternal;
extern vboData_protoDefaultTypeInternal _vboData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<14> vboData_proto_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::vboData_proto_VBO_COMPONENT_internal_data_>
    internal::EnumTraitsImpl::value<::vboData_proto_VBO_COMPONENT>;
template <>
internal::EnumTraitsT<::vboData_proto_VBO_TARGET_internal_data_>
    internal::EnumTraitsImpl::value<::vboData_proto_VBO_TARGET>;
template <>
internal::EnumTraitsT<::vboData_proto_VBO_TYPE_internal_data_>
    internal::EnumTraitsImpl::value<::vboData_proto_VBO_TYPE>;
}  // namespace protobuf
}  // namespace google

enum vboData_proto_VBO_TARGET : int {
  vboData_proto_VBO_TARGET_ARRAY_BUFFER = 0,
  vboData_proto_VBO_TARGET_ELEMENT_ARRAY_BUFFER = 1,
  vboData_proto_VBO_TARGET_vboData_proto_VBO_TARGET_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  vboData_proto_VBO_TARGET_vboData_proto_VBO_TARGET_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t vboData_proto_VBO_TARGET_internal_data_[];
inline constexpr vboData_proto_VBO_TARGET vboData_proto_VBO_TARGET_VBO_TARGET_MIN =
    static_cast<vboData_proto_VBO_TARGET>(0);
inline constexpr vboData_proto_VBO_TARGET vboData_proto_VBO_TARGET_VBO_TARGET_MAX =
    static_cast<vboData_proto_VBO_TARGET>(1);
inline bool vboData_proto_VBO_TARGET_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int vboData_proto_VBO_TARGET_VBO_TARGET_ARRAYSIZE = 1 + 1;
const ::std::string& vboData_proto_VBO_TARGET_Name(vboData_proto_VBO_TARGET value);
template <typename T>
const ::std::string& vboData_proto_VBO_TARGET_Name(T value) {
  static_assert(::std::is_same<T, vboData_proto_VBO_TARGET>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to VBO_TARGET_Name().");
  return vboData_proto_VBO_TARGET_Name(static_cast<vboData_proto_VBO_TARGET>(value));
}
bool vboData_proto_VBO_TARGET_Parse(
    ::absl::string_view name, vboData_proto_VBO_TARGET* PROTOBUF_NONNULL value);
enum vboData_proto_VBO_COMPONENT : int {
  vboData_proto_VBO_COMPONENT_BYTE = 0,
  vboData_proto_VBO_COMPONENT_UNSIGNED_BYTE = 1,
  vboData_proto_VBO_COMPONENT_SHORT = 2,
  vboData_proto_VBO_COMPONENT_UNSIGNED_SHORT = 3,
  vboData_proto_VBO_COMPONENT_INT = 4,
  vboData_proto_VBO_COMPONENT_UNSIGNED_INT = 5,
  vboData_proto_VBO_COMPONENT_FLOAT = 6,
  vboData_proto_VBO_COMPONENT_DOUBLE = 7,
  vboData_proto_VBO_COMPONENT_vboData_proto_VBO_COMPONENT_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  vboData_proto_VBO_COMPONENT_vboData_proto_VBO_COMPONENT_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t vboData_proto_VBO_COMPONENT_internal_data_[];
inline constexpr vboData_proto_VBO_COMPONENT vboData_proto_VBO_COMPONENT_VBO_COMPONENT_MIN =
    static_cast<vboData_proto_VBO_COMPONENT>(0);
inline constexpr vboData_proto_VBO_COMPONENT vboData_proto_VBO_COMPONENT_VBO_COMPONENT_MAX =
    static_cast<vboData_proto_VBO_COMPONENT>(7);
inline bool vboData_proto_VBO_COMPONENT_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int vboData_proto_VBO_COMPONENT_VBO_COMPONENT_ARRAYSIZE = 7 + 1;
const ::std::string& vboData_proto_VBO_COMPONENT_Name(vboData_proto_VBO_COMPONENT value);
template <typename T>
const ::std::string& vboData_proto_VBO_COMPONENT_Name(T value) {
  static_assert(::std::is_same<T, vboData_proto_VBO_COMPONENT>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to VBO_COMPONENT_Name().");
  return vboData_proto_VBO_COMPONENT_Name(static_cast<vboData_proto_VBO_COMPONENT>(value));
}
bool vboData_proto_VBO_COMPONENT_Parse(
    ::absl::string_view name, vboData_proto_VBO_COMPONENT* PROTOBUF_NONNULL value);
enum vboData_proto_VBO_TYPE : int {
  vboData_proto_VBO_TYPE_VEC2 = 0,
  vboData_proto_VBO_TYPE_VEC3 = 1,
  vboData_proto_VBO_TYPE_VEC4 = 2,
  vboData_proto_VBO_TYPE_MAT2 = 3,
  vboData_proto_VBO_TYPE_MAT3 = 4,
  vboData_proto_VBO_TYPE_MAT4 = 5,
  vboData_proto_VBO_TYPE_SCALAR = 6,
  vboData_proto_VBO_TYPE_VECTOR = 7,
  vboData_proto_VBO_TYPE_MATRIX = 8,
  vboData_proto_VBO_TYPE_vboData_proto_VBO_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  vboData_proto_VBO_TYPE_vboData_proto_VBO_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t vboData_proto_VBO_TYPE_internal_data_[];
inline constexpr vboData_proto_VBO_TYPE vboData_proto_VBO_TYPE_VBO_TYPE_MIN =
    static_cast<vboData_proto_VBO_TYPE>(0);
inline constexpr vboData_proto_VBO_TYPE vboData_proto_VBO_TYPE_VBO_TYPE_MAX =
    static_cast<vboData_proto_VBO_TYPE>(8);
inline bool vboData_proto_VBO_TYPE_IsValid(int value) {
  return 0 <= value && value <= 8;
}
inline constexpr int vboData_proto_VBO_TYPE_VBO_TYPE_ARRAYSIZE = 8 + 1;
const ::std::string& vboData_proto_VBO_TYPE_Name(vboData_proto_VBO_TYPE value);
template <typename T>
const ::std::string& vboData_proto_VBO_TYPE_Name(T value) {
  static_assert(::std::is_same<T, vboData_proto_VBO_TYPE>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to VBO_TYPE_Name().");
  return vboData_proto_VBO_TYPE_Name(static_cast<vboData_proto_VBO_TYPE>(value));
}
bool vboData_proto_VBO_TYPE_Parse(
    ::absl::string_view name, vboData_proto_VBO_TYPE* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class vboData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:vboData_proto) */ {
 public:
  inline vboData_proto() : vboData_proto(nullptr) {}
  ~vboData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(vboData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(vboData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR vboData_proto(::google::protobuf::internal::ConstantInitialized);

  inline vboData_proto(const vboData_proto& from) : vboData_proto(nullptr, from) {}
  inline vboData_proto(vboData_proto&& from) noexcept
      : vboData_proto(nullptr, ::std::move(from)) {}
  inline vboData_proto& operator=(const vboData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline vboData_proto& operator=(vboData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const vboData_proto& default_instance() {
    return *reinterpret_cast<const vboData_proto*>(
        &_vboData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(vboData_proto& a, vboData_proto& b) { a.Swap(&b); }
  inline void Swap(vboData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(vboData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  vboData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<vboData_proto>(arena);
  }
  void CopyFrom(const vboData_proto& from);
  void MergeFrom(const vboData_proto& from) { vboData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(vboData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vboData_proto"; }

 protected:
  explicit vboData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  vboData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const vboData_proto& from);
  vboData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, vboData_proto&& from) noexcept
      : vboData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using VBO_TARGET = vboData_proto_VBO_TARGET;
  static constexpr VBO_TARGET ARRAY_BUFFER = vboData_proto_VBO_TARGET_ARRAY_BUFFER;
  static constexpr VBO_TARGET ELEMENT_ARRAY_BUFFER = vboData_proto_VBO_TARGET_ELEMENT_ARRAY_BUFFER;
  static inline bool VBO_TARGET_IsValid(int value) {
    return vboData_proto_VBO_TARGET_IsValid(value);
  }
  static constexpr VBO_TARGET VBO_TARGET_MIN = vboData_proto_VBO_TARGET_VBO_TARGET_MIN;
  static constexpr VBO_TARGET VBO_TARGET_MAX = vboData_proto_VBO_TARGET_VBO_TARGET_MAX;
  static constexpr int VBO_TARGET_ARRAYSIZE = vboData_proto_VBO_TARGET_VBO_TARGET_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& VBO_TARGET_Name(T value) {
    return vboData_proto_VBO_TARGET_Name(value);
  }
  static inline bool VBO_TARGET_Parse(
      ::absl::string_view name, VBO_TARGET* PROTOBUF_NONNULL value) {
    return vboData_proto_VBO_TARGET_Parse(name, value);
  }
  using VBO_COMPONENT = vboData_proto_VBO_COMPONENT;
  static constexpr VBO_COMPONENT BYTE = vboData_proto_VBO_COMPONENT_BYTE;
  static constexpr VBO_COMPONENT UNSIGNED_BYTE = vboData_proto_VBO_COMPONENT_UNSIGNED_BYTE;
  static constexpr VBO_COMPONENT SHORT = vboData_proto_VBO_COMPONENT_SHORT;
  static constexpr VBO_COMPONENT UNSIGNED_SHORT = vboData_proto_VBO_COMPONENT_UNSIGNED_SHORT;
  static constexpr VBO_COMPONENT INT = vboData_proto_VBO_COMPONENT_INT;
  static constexpr VBO_COMPONENT UNSIGNED_INT = vboData_proto_VBO_COMPONENT_UNSIGNED_INT;
  static constexpr VBO_COMPONENT FLOAT = vboData_proto_VBO_COMPONENT_FLOAT;
  static constexpr VBO_COMPONENT DOUBLE = vboData_proto_VBO_COMPONENT_DOUBLE;
  static inline bool VBO_COMPONENT_IsValid(int value) {
    return vboData_proto_VBO_COMPONENT_IsValid(value);
  }
  static constexpr VBO_COMPONENT VBO_COMPONENT_MIN = vboData_proto_VBO_COMPONENT_VBO_COMPONENT_MIN;
  static constexpr VBO_COMPONENT VBO_COMPONENT_MAX = vboData_proto_VBO_COMPONENT_VBO_COMPONENT_MAX;
  static constexpr int VBO_COMPONENT_ARRAYSIZE = vboData_proto_VBO_COMPONENT_VBO_COMPONENT_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& VBO_COMPONENT_Name(T value) {
    return vboData_proto_VBO_COMPONENT_Name(value);
  }
  static inline bool VBO_COMPONENT_Parse(
      ::absl::string_view name, VBO_COMPONENT* PROTOBUF_NONNULL value) {
    return vboData_proto_VBO_COMPONENT_Parse(name, value);
  }
  using VBO_TYPE = vboData_proto_VBO_TYPE;
  static constexpr VBO_TYPE VEC2 = vboData_proto_VBO_TYPE_VEC2;
  static constexpr VBO_TYPE VEC3 = vboData_proto_VBO_TYPE_VEC3;
  static constexpr VBO_TYPE VEC4 = vboData_proto_VBO_TYPE_VEC4;
  static constexpr VBO_TYPE MAT2 = vboData_proto_VBO_TYPE_MAT2;
  static constexpr VBO_TYPE MAT3 = vboData_proto_VBO_TYPE_MAT3;
  static constexpr VBO_TYPE MAT4 = vboData_proto_VBO_TYPE_MAT4;
  static constexpr VBO_TYPE SCALAR = vboData_proto_VBO_TYPE_SCALAR;
  static constexpr VBO_TYPE VECTOR = vboData_proto_VBO_TYPE_VECTOR;
  static constexpr VBO_TYPE MATRIX = vboData_proto_VBO_TYPE_MATRIX;
  static inline bool VBO_TYPE_IsValid(int value) {
    return vboData_proto_VBO_TYPE_IsValid(value);
  }
  static constexpr VBO_TYPE VBO_TYPE_MIN = vboData_proto_VBO_TYPE_VBO_TYPE_MIN;
  static constexpr VBO_TYPE VBO_TYPE_MAX = vboData_proto_VBO_TYPE_VBO_TYPE_MAX;
  static constexpr int VBO_TYPE_ARRAYSIZE = vboData_proto_VBO_TYPE_VBO_TYPE_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& VBO_TYPE_Name(T value) {
    return vboData_proto_VBO_TYPE_Name(value);
  }
  static inline bool VBO_TYPE_Parse(
      ::absl::string_view name, VBO_TYPE* PROTOBUF_NONNULL value) {
    return vboData_proto_VBO_TYPE_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPoDataFieldNumber = 8,
    kEnabledFieldNumber = 1,
    kTargetTypeFieldNumber = 2,
    kComponentTypeFieldNumber = 3,
    kVboTypeFieldNumber = 4,
    kStrideFieldNumber = 5,
    kCountFieldNumber = 6,
    kDataSizeFieldNumber = 7,
  };
  // optional bytes poData = 8;
  bool has_podata() const;
  void clear_podata() ;
  const ::std::string& podata() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_podata(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_podata();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_podata();
  void set_allocated_podata(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_podata() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_podata(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_podata();

  public:
  // optional uint32 enabled = 1;
  bool has_enabled() const;
  void clear_enabled() ;
  ::uint32_t enabled() const;
  void set_enabled(::uint32_t value);

  private:
  ::uint32_t _internal_enabled() const;
  void _internal_set_enabled(::uint32_t value);

  public:
  // optional .vboData_proto.VBO_TARGET targetType = 2;
  bool has_targettype() const;
  void clear_targettype() ;
  ::vboData_proto_VBO_TARGET targettype() const;
  void set_targettype(::vboData_proto_VBO_TARGET value);

  private:
  ::vboData_proto_VBO_TARGET _internal_targettype() const;
  void _internal_set_targettype(::vboData_proto_VBO_TARGET value);

  public:
  // optional .vboData_proto.VBO_COMPONENT componentType = 3;
  bool has_componenttype() const;
  void clear_componenttype() ;
  ::vboData_proto_VBO_COMPONENT componenttype() const;
  void set_componenttype(::vboData_proto_VBO_COMPONENT value);

  private:
  ::vboData_proto_VBO_COMPONENT _internal_componenttype() const;
  void _internal_set_componenttype(::vboData_proto_VBO_COMPONENT value);

  public:
  // optional .vboData_proto.VBO_TYPE vboType = 4;
  bool has_vbotype() const;
  void clear_vbotype() ;
  ::vboData_proto_VBO_TYPE vbotype() const;
  void set_vbotype(::vboData_proto_VBO_TYPE value);

  private:
  ::vboData_proto_VBO_TYPE _internal_vbotype() const;
  void _internal_set_vbotype(::vboData_proto_VBO_TYPE value);

  public:
  // optional uint32 stride = 5;
  bool has_stride() const;
  void clear_stride() ;
  ::uint32_t stride() const;
  void set_stride(::uint32_t value);

  private:
  ::uint32_t _internal_stride() const;
  void _internal_set_stride(::uint32_t value);

  public:
  // optional uint32 count = 6;
  bool has_count() const;
  void clear_count() ;
  ::uint32_t count() const;
  void set_count(::uint32_t value);

  private:
  ::uint32_t _internal_count() const;
  void _internal_set_count(::uint32_t value);

  public:
  // optional uint32 dataSize = 7;
  bool has_datasize() const;
  void clear_datasize() ;
  ::uint32_t datasize() const;
  void set_datasize(::uint32_t value);

  private:
  ::uint32_t _internal_datasize() const;
  void _internal_set_datasize(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:vboData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const vboData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr podata_;
    ::uint32_t enabled_;
    int targettype_;
    int componenttype_;
    int vbotype_;
    ::uint32_t stride_;
    ::uint32_t count_;
    ::uint32_t datasize_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vboData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<14> vboData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// vboData_proto

// optional uint32 enabled = 1;
inline bool vboData_proto::has_enabled() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void vboData_proto::clear_enabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enabled_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t vboData_proto::enabled() const {
  // @@protoc_insertion_point(field_get:vboData_proto.enabled)
  return _internal_enabled();
}
inline void vboData_proto::set_enabled(::uint32_t value) {
  _internal_set_enabled(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:vboData_proto.enabled)
}
inline ::uint32_t vboData_proto::_internal_enabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enabled_;
}
inline void vboData_proto::_internal_set_enabled(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enabled_ = value;
}

// optional .vboData_proto.VBO_TARGET targetType = 2;
inline bool vboData_proto::has_targettype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void vboData_proto::clear_targettype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targettype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::vboData_proto_VBO_TARGET vboData_proto::targettype() const {
  // @@protoc_insertion_point(field_get:vboData_proto.targetType)
  return _internal_targettype();
}
inline void vboData_proto::set_targettype(::vboData_proto_VBO_TARGET value) {
  _internal_set_targettype(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:vboData_proto.targetType)
}
inline ::vboData_proto_VBO_TARGET vboData_proto::_internal_targettype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vboData_proto_VBO_TARGET>(_impl_.targettype_);
}
inline void vboData_proto::_internal_set_targettype(::vboData_proto_VBO_TARGET value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targettype_ = value;
}

// optional .vboData_proto.VBO_COMPONENT componentType = 3;
inline bool vboData_proto::has_componenttype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void vboData_proto::clear_componenttype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.componenttype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline ::vboData_proto_VBO_COMPONENT vboData_proto::componenttype() const {
  // @@protoc_insertion_point(field_get:vboData_proto.componentType)
  return _internal_componenttype();
}
inline void vboData_proto::set_componenttype(::vboData_proto_VBO_COMPONENT value) {
  _internal_set_componenttype(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:vboData_proto.componentType)
}
inline ::vboData_proto_VBO_COMPONENT vboData_proto::_internal_componenttype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vboData_proto_VBO_COMPONENT>(_impl_.componenttype_);
}
inline void vboData_proto::_internal_set_componenttype(::vboData_proto_VBO_COMPONENT value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.componenttype_ = value;
}

// optional .vboData_proto.VBO_TYPE vboType = 4;
inline bool vboData_proto::has_vbotype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010U) != 0;
  return value;
}
inline void vboData_proto::clear_vbotype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbotype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline ::vboData_proto_VBO_TYPE vboData_proto::vbotype() const {
  // @@protoc_insertion_point(field_get:vboData_proto.vboType)
  return _internal_vbotype();
}
inline void vboData_proto::set_vbotype(::vboData_proto_VBO_TYPE value) {
  _internal_set_vbotype(value);
  _impl_._has_bits_[0] |= 0x00000010U;
  // @@protoc_insertion_point(field_set:vboData_proto.vboType)
}
inline ::vboData_proto_VBO_TYPE vboData_proto::_internal_vbotype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vboData_proto_VBO_TYPE>(_impl_.vbotype_);
}
inline void vboData_proto::_internal_set_vbotype(::vboData_proto_VBO_TYPE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vbotype_ = value;
}

// optional uint32 stride = 5;
inline bool vboData_proto::has_stride() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020U) != 0;
  return value;
}
inline void vboData_proto::clear_stride() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stride_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline ::uint32_t vboData_proto::stride() const {
  // @@protoc_insertion_point(field_get:vboData_proto.stride)
  return _internal_stride();
}
inline void vboData_proto::set_stride(::uint32_t value) {
  _internal_set_stride(value);
  _impl_._has_bits_[0] |= 0x00000020U;
  // @@protoc_insertion_point(field_set:vboData_proto.stride)
}
inline ::uint32_t vboData_proto::_internal_stride() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stride_;
}
inline void vboData_proto::_internal_set_stride(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stride_ = value;
}

// optional uint32 count = 6;
inline bool vboData_proto::has_count() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040U) != 0;
  return value;
}
inline void vboData_proto::clear_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline ::uint32_t vboData_proto::count() const {
  // @@protoc_insertion_point(field_get:vboData_proto.count)
  return _internal_count();
}
inline void vboData_proto::set_count(::uint32_t value) {
  _internal_set_count(value);
  _impl_._has_bits_[0] |= 0x00000040U;
  // @@protoc_insertion_point(field_set:vboData_proto.count)
}
inline ::uint32_t vboData_proto::_internal_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_;
}
inline void vboData_proto::_internal_set_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = value;
}

// optional uint32 dataSize = 7;
inline bool vboData_proto::has_datasize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080U) != 0;
  return value;
}
inline void vboData_proto::clear_datasize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datasize_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000080U;
}
inline ::uint32_t vboData_proto::datasize() const {
  // @@protoc_insertion_point(field_get:vboData_proto.dataSize)
  return _internal_datasize();
}
inline void vboData_proto::set_datasize(::uint32_t value) {
  _internal_set_datasize(value);
  _impl_._has_bits_[0] |= 0x00000080U;
  // @@protoc_insertion_point(field_set:vboData_proto.dataSize)
}
inline ::uint32_t vboData_proto::_internal_datasize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.datasize_;
}
inline void vboData_proto::_internal_set_datasize(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datasize_ = value;
}

// optional bytes poData = 8;
inline bool vboData_proto::has_podata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void vboData_proto::clear_podata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.podata_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& vboData_proto::podata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vboData_proto.poData)
  return _internal_podata();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void vboData_proto::set_podata(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.podata_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vboData_proto.poData)
}
inline ::std::string* PROTOBUF_NONNULL vboData_proto::mutable_podata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_podata();
  // @@protoc_insertion_point(field_mutable:vboData_proto.poData)
  return _s;
}
inline const ::std::string& vboData_proto::_internal_podata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.podata_.Get();
}
inline void vboData_proto::_internal_set_podata(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.podata_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL vboData_proto::_internal_mutable_podata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.podata_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE vboData_proto::release_podata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vboData_proto.poData)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.podata_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.podata_.Set("", GetArena());
  }
  return released;
}
inline void vboData_proto::set_allocated_podata(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.podata_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.podata_.IsDefault()) {
    _impl_.podata_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vboData_proto.poData)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::vboData_proto_VBO_TARGET> : std::true_type {};
template <>
struct is_proto_enum<::vboData_proto_VBO_COMPONENT> : std::true_type {};
template <>
struct is_proto_enum<::vboData_proto_VBO_TYPE> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // vboData_2eproto_2epb_2eh
